//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCandidateListTouchBarItem.h>

@interface _AutoCompleteTouchBarItem : NSCandidateListTouchBarItem
{
}

- (id)makeViewForCustomizationPalette;	// IMP=0x00000000000173ee

@end

