//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface _MUISnapshotView : NSView
{
}

- (id)hitTest:(struct CGPoint)arg1;	// IMP=0x00000000000268ac
- (BOOL)isFlipped;	// IMP=0x0000000000005e30

@end

