//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

@interface _MUIAddContactsButton : NSButton
{
}

- (BOOL)acceptsFirstResponder;	// IMP=0x000000000000fc87

@end

