//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailUI/NSObject-Protocol.h>

@class CNContact, NSString;

@protocol EMBlockedSenderTokenAddress <NSObject>
@property(readonly, copy, nonatomic) NSString *currentRawAddress;
@property(readonly, nonatomic) CNContact *contact;
@end

