//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSURLProtocol.h>

@interface MUIBundleResourceURLProtocol : NSURLProtocol
{
}

+ (BOOL)requestIsCacheEquivalent:(id)arg1 toRequest:(id)arg2;	// IMP=0x0000000000017783
+ (id)canonicalRequestForRequest:(id)arg1;	// IMP=0x00000000000105c0
+ (BOOL)canInitWithRequest:(id)arg1;	// IMP=0x000000000000daaa
- (void)stopLoading;	// IMP=0x0000000000010951
- (void)startLoading;	// IMP=0x00000000000105d6

@end

