//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MUIFramework : NSObject
{
}

+ (id)bundle;	// IMP=0x0000000000005af6

@end

