//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailUI/EFLoggable-Protocol.h>

@class NSString;

@interface MUIOpenWithApplicationHelper : NSObject <EFLoggable>
{
}

+ (id)openWithMenuItemForAttachmentURLs:(id)arg1;	// IMP=0x000000000001d29d
+ (id)openWithMenuItemForAttachmentURLs:(id)arg1 selectionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000000001cfb1
+ (id)log;	// IMP=0x000000000001cee8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

