//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSToolbarItem.h>

@class NSSegmentedControl;

@interface MUISegmentedToolbarItem : NSToolbarItem
{
}

- (void)sizeToFit;	// IMP=0x000000000001e3a5
- (void)validate;	// IMP=0x000000000001e264
@property(retain) NSSegmentedControl *view;
- (id)initWithDictionaryRepresentation:(id)arg1;	// IMP=0x000000000001df7b

@end

