//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTokenFieldCell.h>

@interface MUITokenAddressFieldCell : NSTokenFieldCell
{
}

- (BOOL)_needRedrawOnWindowChangedKeyState;	// IMP=0x000000000000da9f
- (BOOL)tokenAttachment:(id)arg1 doubleClickedInRect:(struct CGRect)arg2 ofView:(id)arg3 atCharacterIndex:(unsigned long long)arg4;	// IMP=0x0000000000023d70
- (id)_fieldEditor;	// IMP=0x000000000000c9b3

@end

