//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSConcreteTextStorage.h>

@interface MUITokenAddressTextStorage : NSConcreteTextStorage
{
}

- (BOOL)stripsFontAndColorFromAttachments;	// IMP=0x0000000000023eb8

@end

