//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailUI/NSObject-Protocol.h>

@class NSData, NSString;

@protocol MUIWKWebViewUIProxyObject <NSObject>
- (void)setDocumentElementDirection:(long long)arg1;
- (void)dataDetectorsExternalUIRequested:(NSData *)arg1;
- (void)logInjectedWebBundleMessage:(NSString *)arg1;
- (void)logWebConsoleMessage:(NSString *)arg1;
- (void)setMessageHasBlockedMessageContent;
- (void)completeWebDocumentPasteboardType;
@end

