//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailUI/NSObject-Protocol.h>

@class NSValue;

@protocol MUIWKWebViewWebProxyObject <NSObject>
- (void)cacheDisplayInRect:(NSValue *)arg1 completionHandler:(void (^)(NSImage *))arg2;
- (void)generateSelectionHTML:(void (^)(NSString *))arg1;
- (void)generateStyleInlinedHTML:(void (^)(NSString *))arg1;
- (void)dataDetectorsExternalUIStopped;
- (void)dataDetectorsExternalUIChanged;
- (void)dataDetectorsExternalUIStarted;
- (void)selectionAndClickInformationForClickAtPoint:(NSValue *)arg1 completionHandler:(void (^)(NSDictionary *))arg2;
@end

