//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSUserDefaults.h>

@class NSString;

@interface NSUserDefaults (FontAdditions)
@property double messageListFontSize;
@property(retain) NSString *messageListFontName;
- (void)setMessageListFont:(id)arg1;	// IMP=0x000000000001a000
- (id)messageListFont;	// IMP=0x0000000000019f82
@end

