//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWorkspace.h>

@interface NSWorkspace (MailUIAdditions)
- (void)mui_openURLsAsynchronously:(id)arg1 withApplicationAtURL:(id)arg2 options:(unsigned long long)arg3;	// IMP=0x000000000001cd6f
@end

