//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/WKProcessPool.h>

@interface WKProcessPool (MailUIAdditions)
+ (id)mui_processPool;	// IMP=0x00000000000291ef
@end

