//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSEnumerator.h>

@class EAEmailAddressSet;

@interface _EAEmailAddressSetEnumerator : NSEnumerator
{
    EAEmailAddressSet *_set;	// 8 = 0x8
    CDStruct_58648341 _state;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000000007d61
- (id)nextObject;	// IMP=0x0000000000007d06
- (unsigned long long)countByEnumeratingWithState:(CDStruct_58648341 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;	// IMP=0x0000000000007ce9
- (id)initWithSet:(id)arg1;	// IMP=0x0000000000007c65

@end

