//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface EAEmailAddressGenerator : NSObject
{
}

+ (id)stringByTrimmingCommasSpacesQuotesFromString:(id)arg1;	// IMP=0x00000000000019ba
+ (id)formattedAddressWithName:(id)arg1 email:(id)arg2 useQuotes:(BOOL)arg3;	// IMP=0x00000000000016af

@end

