//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/NSObject-Protocol.h>

@class _MCBatchingTimer;

@protocol _MCBatchingTimerDelegate <NSObject>
- (void)batchingTimerDidFire:(_MCBatchingTimer *)arg1;
@end

