//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageRep.h>

@class NSArray;

@interface _MCCompositeImageRep : NSImageRep
{
    NSArray *_arrayOfImageDictionaries;	// 8 = 0x8
}

@property(copy, nonatomic) NSArray *arrayOfImageDictionaries; // @synthesize arrayOfImageDictionaries=_arrayOfImageDictionaries;
- (void).cxx_destruct;	// IMP=0x0000000000088f1f
- (BOOL)draw;	// IMP=0x0000000000088afb

@end

