//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCMessage.h>

@class MCMemoryDataSource;

@interface _MCMemoryMessage : MCMessage
{
    MCMemoryDataSource *_dataSource;	// 104 = 0x68
}

- (void).cxx_destruct;	// IMP=0x0000000000057789
- (BOOL)isCompacted;	// IMP=0x0000000000057781
- (id)messageDataFetchIfNotAvailable:(BOOL)arg1 newDocumentID:(id)arg2;	// IMP=0x00000000000576f5
- (id)primitiveDataSource;	// IMP=0x00000000000576e0
- (void)setDataSource:(id)arg1;	// IMP=0x0000000000057598
- (id)dataSource;	// IMP=0x0000000000057583
- (id)init;	// IMP=0x000000000005756f
- (id)initWithStore:(id)arg1;	// IMP=0x0000000000057501

@end

