//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _MCMimeEnrichedReaderCommandStackEntry : NSObject
{
    const CDStruct_8e792ae2 *_commandTableEntry;	// 8 = 0x8
    id _parameter;	// 16 = 0x10
}

@property(retain, nonatomic) id parameter; // @synthesize parameter=_parameter;
@property(nonatomic) const CDStruct_8e792ae2 *commandTableEntry; // @synthesize commandTableEntry=_commandTableEntry;
- (void).cxx_destruct;	// IMP=0x000000000006c219

@end

