//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AddressBook/ABAddressBook.h>

@interface ABAddressBook (MailCoreAdditions)
+ (BOOL)_firstNameShouldBeFirstForRecord:(id)arg1;	// IMP=0x0000000000038cb8
- (id)bestRecordMatchingFormattedAddress:(id)arg1;	// IMP=0x0000000000038610
@end

