//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AddressBook/ABGroup.h>

@interface ABGroup (MailCoreAdditions)
+ (id)diacriticInsensitiveSearchElementForProperty:(id)arg1 label:(id)arg2 key:(id)arg3 value:(id)arg4 comparison:(long long)arg5;	// IMP=0x000000000003825b
- (BOOL)hasEmailAddress:(id)arg1;	// IMP=0x00000000000381e3
- (id)_fullName;	// IMP=0x00000000000381d1
- (BOOL)isGroup;	// IMP=0x00000000000381c6
@end

