//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AddressBook/ABMailRecent.h>

@class NSDate;

@interface ABMailRecent (MailCoreAdditions)
- (id)_fullName;	// IMP=0x0000000000038495
- (BOOL)isGroup;	// IMP=0x00000000000383e1
@property(readonly, nonatomic) BOOL hasRelatedAddressBookRecord;
@property(readonly, nonatomic) NSDate *mostRecentDate;
- (id)extension;	// IMP=0x000000000003832f
- (id)nickname;	// IMP=0x0000000000038327
- (id)middleName;	// IMP=0x000000000003831f
@end

