//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AddressBook/ABPerson.h>

@interface ABPerson (MailCoreAdditions)
+ (id)diacriticInsensitiveSearchElementForProperty:(id)arg1 label:(id)arg2 key:(id)arg3 value:(id)arg4 comparison:(long long)arg5;	// IMP=0x0000000000038102
- (BOOL)isGroup;	// IMP=0x00000000000380fa
- (id)compoundNameAndEmailForGroupMembership:(id)arg1;	// IMP=0x0000000000037f95
@property(readonly, nonatomic) BOOL isMe;
- (BOOL)hasEmailAddress:(id)arg1;	// IMP=0x0000000000037db3
@end

