//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Contacts/CNContact.h>

@interface CNContact (Additions)
- (BOOL)hasEmailAddress:(id)arg1;	// IMP=0x0000000000047f55
@end

