//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextAttachment.h>

@class MCAttachment, MCFileWrapper;

@interface MCAttachmentWrappingTextAttachment : NSTextAttachment
{
    MCAttachment *_messageAttachment;	// 32 = 0x20
}

@property(readonly, nonatomic) MCAttachment *messageAttachment; // @synthesize messageAttachment=_messageAttachment;
- (void).cxx_destruct;	// IMP=0x0000000000042918
@property(retain) MCFileWrapper *fileWrapper;
- (id)initWithFileWrapper:(id)arg1;	// IMP=0x00000000000426cc
- (id)initWithData:(id)arg1 ofType:(id)arg2;	// IMP=0x00000000000425fd
- (id)initWithAttachment:(id)arg1;	// IMP=0x000000000004258b

@end

