//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/NSObject-Protocol.h>

@class NSArray;
@protocol MCBodyTracker;

@protocol MCBodyTracker <NSObject>
- (void)bodyTracker:(id <MCBodyTracker>)arg1 didCacheBodiesForMessages:(NSArray *)arg2;
@end

