//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCProgressEntry.h>

@interface MCByteStatusProgressEntry : MCProgressEntry
{
    long long _totalBytes;	// 8 = 0x8
}

+ (id)keyPathsForValuesAffectingStatusText;	// IMP=0x00000000000429fa
@property(nonatomic) long long totalBytes; // @synthesize totalBytes=_totalBytes;
- (void)refreshValues;	// IMP=0x0000000000042b35
- (id)observedProgressKeyPaths;	// IMP=0x0000000000042a8b
- (BOOL)indeterminate;	// IMP=0x0000000000042a83
- (id)statusText;	// IMP=0x0000000000042a1a

@end

