//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCProgressEntry.h>

@class NSArray;

@interface MCConnectingProgressEntry : MCProgressEntry
{
    NSArray *_connectingAccountNames;	// 8 = 0x8
}

+ (id)keyPathsForValuesAffectingStatusText;	// IMP=0x0000000000043dad
@property(copy, nonatomic) NSArray *connectingAccountNames; // @synthesize connectingAccountNames=_connectingAccountNames;
- (void).cxx_destruct;	// IMP=0x0000000000043e71
- (BOOL)indeterminate;	// IMP=0x0000000000043e42
- (id)statusText;	// IMP=0x0000000000043dcd
- (id)progressSlice;	// IMP=0x0000000000043d8f
- (id)progressName;	// IMP=0x0000000000043ced
- (void)refreshValues;	// IMP=0x00000000000438a6
- (id)observedProgressKeypaths;	// IMP=0x00000000000437fc

@end

