//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MCDateClassifier : NSObject
{
}

+ (BOOL)isYesterday:(id)arg1;	// IMP=0x0000000000048def
+ (BOOL)isToday:(id)arg1;	// IMP=0x0000000000048dba
+ (void)_resetDates;	// IMP=0x0000000000048c85
+ (void)_dateInvalidated:(id)arg1;	// IMP=0x0000000000048c73
+ (void)initialize;	// IMP=0x0000000000048bb9

@end

