//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCProgressEntry.h>

@interface MCDeterminateUnitProgressEntry : MCProgressEntry
{
}

+ (id)keyPathsForValuesAffectingStatusText;	// IMP=0x0000000000049520
- (BOOL)indeterminate;	// IMP=0x0000000000049624
- (id)statusText;	// IMP=0x000000000004954c

@end

