//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCDeterminateUnitProgressEntry.h>

@interface MCDownloadingMessagesProgressEntry : MCDeterminateUnitProgressEntry
{
}

+ (id)keyPathsAffectingValuesForProgressName;	// IMP=0x000000000004a7c3
- (long long)_significantMessageCount;	// IMP=0x000000000004a917
- (BOOL)hasSignificantDeferrableWork;	// IMP=0x000000000004a8c2
- (id)progressSlice;	// IMP=0x000000000004a8a4
- (id)progressName;	// IMP=0x000000000004a7e3

@end

