//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/NSObject-Protocol.h>

@class MCTaskHandler, MCTaskHandlerOperation, NSOperationQueue;

@protocol MCHandlerDelegate <NSObject>
@property(readonly, nonatomic) NSOperationQueue *serializationQueue;
- (void)handlerDidCleanUp:(MCTaskHandler *)arg1;
- (void)handler:(MCTaskHandler *)arg1 didFinishOperation:(MCTaskHandlerOperation *)arg2;
@end

