//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSURLProtocol.h>

@interface MCMessageURLProtocol : NSURLProtocol
{
}

+ (BOOL)requestIsCacheEquivalent:(id)arg1 toRequest:(id)arg2;	// IMP=0x000000000006b441
+ (id)canonicalRequestForRequest:(id)arg1;	// IMP=0x000000000006b42b
+ (BOOL)canInitWithRequest:(id)arg1;	// IMP=0x000000000002c138
- (void)stopLoading;	// IMP=0x000000000006b4e4
- (void)startLoading;	// IMP=0x000000000006b449

@end

