//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MCMimeDataEncoding : NSObject
{
}

+ (id)sharedKeySetForEncodingOptions;	// IMP=0x000000000000ad94

@end

