//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCDeterminateUnitProgressEntry.h>

@interface MCMovingMessagesProgressEntry : MCDeterminateUnitProgressEntry
{
}

+ (id)keyPathsAffectingValuesForProgressName;	// IMP=0x000000000008064f
- (id)progressSlice;	// IMP=0x000000000008072d
- (id)progressName;	// IMP=0x000000000008066f

@end

