//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class MCActivityMonitor, NSString;

@interface MCMonitoredOperation : NSOperation
{
    MCActivityMonitor *_parentMonitor;	// 8 = 0x8
    MCActivityMonitor *_monitor;	// 16 = 0x10
}

@property(retain, nonatomic) MCActivityMonitor *monitor; // @synthesize monitor=_monitor;
@property(retain, nonatomic) MCActivityMonitor *parentMonitor; // @synthesize parentMonitor=_parentMonitor;
- (void).cxx_destruct;	// IMP=0x000000000008061e
- (void)executeOperation;	// IMP=0x00000000000805ce
@property(readonly, copy, nonatomic) NSString *activityString;
- (void)main;	// IMP=0x00000000000804a9
- (void)dealloc;	// IMP=0x0000000000080415
- (id)init;	// IMP=0x0000000000080395

@end

