//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCFileWrapper.h>

@interface MCPlaceholderFileWrapper : MCFileWrapper
{
}

- (BOOL)isRemotelyAccessed;	// IMP=0x000000000004f3df
- (BOOL)isPlaceholder;	// IMP=0x000000000004f3d4

@end

