//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/NSObject-Protocol.h>

@class MCProgressEntry, NSArray;

@protocol MCProgressEntryDelegate <NSObject>
@property(readonly, copy, nonatomic) NSArray *trackedAccountNames;
- (void)progressEntryDidFinish:(MCProgressEntry *)arg1;
@end

