//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCTransferringMessagesProgressEntry.h>

@interface MCPreparingToCopyProgressEntry : MCTransferringMessagesProgressEntry
{
}

+ (id)keyPathsAffectingValuesForProgressName;	// IMP=0x000000000008a981
- (id)progressSlice;	// IMP=0x000000000008aa5f
- (id)progressName;	// IMP=0x000000000008a9a1

@end

