//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSInvocation.h>

@class NSNumber;

@interface MCQOSInvocation : NSInvocation
{
    NSNumber *_requestedQualityOfService;	// 8 = 0x8
}

@property(retain) NSNumber *requestedQualityOfService; // @synthesize requestedQualityOfService=_requestedQualityOfService;
- (void).cxx_destruct;	// IMP=0x000000000007faa7

@end

