//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCByteStatusProgressEntry.h>

@interface MCSavingDraftProgressEntry : MCByteStatusProgressEntry
{
    BOOL _userInitiated;	// 8 = 0x8
}

+ (id)keyPathsAffectingValuesForShouldDisplay;	// IMP=0x000000000008f7b0
+ (id)keyPathsAffectingValuesForProgressName;	// IMP=0x000000000008f394
@property(nonatomic) BOOL userInitiated; // @synthesize userInitiated=_userInitiated;
- (double)finishDelay;	// IMP=0x000000000008f7e6
- (BOOL)shouldDisplay;	// IMP=0x000000000008f7d4
- (void)refreshValues;	// IMP=0x000000000008f565
- (id)observedProgressKeypaths;	// IMP=0x000000000008f4bb
- (id)progressSlice;	// IMP=0x000000000008f49d
- (id)progressName;	// IMP=0x000000000008f3c0

@end

