//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCByteStatusProgressEntry.h>

@interface MCSendingMessagesProgressEntry : MCByteStatusProgressEntry
{
}

+ (id)keyPathsAffectingValuesForProgressName;	// IMP=0x0000000000096495
- (double)finishDelay;	// IMP=0x00000000000965b9
- (id)progressSlice;	// IMP=0x000000000009659e
- (id)progressName;	// IMP=0x00000000000964c1

@end

