//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSBlockOperation.h>

@class MCActivityMonitor;

@interface MCTaskOperation : NSBlockOperation
{
    MCActivityMonitor *_monitor;	// 8 = 0x8
    MCActivityMonitor *_parentMonitor;	// 16 = 0x10
}

+ (void)setTaskDescription:(const char *)arg1;	// IMP=0x00000000000124d7
@property(retain) MCActivityMonitor *parentMonitor; // @synthesize parentMonitor=_parentMonitor;
@property(retain) MCActivityMonitor *monitor; // @synthesize monitor=_monitor;
- (void).cxx_destruct;	// IMP=0x000000000001351c
- (void)cancel;	// IMP=0x000000000009dd77
- (void)dealloc;	// IMP=0x000000000001338a
- (void)main;	// IMP=0x0000000000012078
- (id)_setTaskName:(id)arg1 priority:(unsigned char)arg2 canCancel:(BOOL)arg3;	// IMP=0x000000000009dc1a
- (void)setParentMonitor:(id)arg1 taskName:(id)arg2;	// IMP=0x0000000000011e03

@end

