//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSInvocationOperation.h>

@interface MCThrowingInvocationOperation : NSInvocationOperation
{
}

- (void)main;	// IMP=0x0000000000003a39

@end

