//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCDeterminateUnitProgressEntry.h>

@interface MCTransferringMessagesProgressEntry : MCDeterminateUnitProgressEntry
{
}

+ (id)keyPathsForValuesAffectingShouldDisplay;	// IMP=0x000000000009dd7d
- (BOOL)shouldDisplay;	// IMP=0x000000000009dd9d

@end

