//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MCURLMatch : NSObject
{
    NSString *_urlString;	// 8 = 0x8
    struct _NSRange _range;	// 16 = 0x10
}

@property(readonly, nonatomic) struct _NSRange range; // @synthesize range=_range;
@property(readonly, copy, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
- (void).cxx_destruct;	// IMP=0x000000000009e0cb
- (id)description;	// IMP=0x000000000009dff2
- (id)debugDescription;	// IMP=0x000000000009df13
- (id)init;	// IMP=0x000000000009de44
- (id)initWithRange:(struct _NSRange)arg1 urlString:(id)arg2;	// IMP=0x000000000009ddbb

@end

