//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MCWorkerThread : NSObject
{
}

+ (void)runInvocationOnQueueSynchronously:(id)arg1;	// IMP=0x000000000009ebc2
+ (void)addInvocationToQueue:(id)arg1;	// IMP=0x0000000000003449
+ (void)initialize;	// IMP=0x00000000000033e5

@end

