//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSArray.h>

@class NSDictionary;

@interface NSArray (MessagesFromMixedStoresConvenience)
@property(readonly, copy, nonatomic) NSDictionary *dictionaryWithMessagesSortedByMailbox;
@property(readonly, copy, nonatomic) NSDictionary *dictionaryWithMessagesSortedByStore;
@end

