//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (MailCoreAdditions)
- (id)replyPrefixForSender:(id)arg1 withSpacer:(BOOL)arg2;	// IMP=0x0000000000086d18
@end

