//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImage.h>

@class NSBitmapImageRep, NSData;

@interface NSImage (MailCoreAdditions)
+ (id)rotateImage:(id)arg1 byDegrees:(double)arg2;	// IMP=0x000000000008858e
+ (id)imageDataForType:(id *)arg1 fromPasteboard:(id)arg2;	// IMP=0x0000000000087e14
+ (id)imagePasteboardTypesWithPreferenceToPNG;	// IMP=0x000000000002b837
+ (id)compositeImageWithImageDictionaries:(id)arg1 size:(struct CGSize)arg2;	// IMP=0x0000000000088a2c
+ (id)drawingDictionaryWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000000088977
@property(readonly, nonatomic) double pixelsHigh;
@property(readonly, nonatomic) double pixelsWide;
@property(readonly, nonatomic) unsigned long long frameCount;
@property(readonly, copy, nonatomic) NSData *PNGData;
@property(readonly, nonatomic) NSBitmapImageRep *bitmapImageRep;
@property(readonly, nonatomic) NSImage *opaqueImage;
- (id)flippedImageForLayoutDirection:(long long)arg1;	// IMP=0x00000000000887e4
- (id)tintedImageWithColor:(id)arg1 size:(struct CGSize)arg2;	// IMP=0x000000000000267a
- (id)tintedImageWithColor:(id)arg1;	// IMP=0x0000000000002615
@end

