//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableData.h>

@interface NSMutableData (MCMimeDataEncoding)
- (void)appendQuotedPrintableDataForHeaderBytes:(const char *)arg1 length:(unsigned long long)arg2;	// IMP=0x000000000006c1d2
- (void)appendRFC2231CompliantValue:(id)arg1 forKey:(id)arg2 withEncodingHint:(unsigned long long)arg3;	// IMP=0x0000000000027661
- (void)convertNetworkLineEndingsToUnix;	// IMP=0x000000000002082a
- (void)appendCString:(const char *)arg1;	// IMP=0x000000000000ee11
@end

