//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableAttributedString.h>

@interface NSMutableAttributedString (MailCoreAdditions)
- (void)changeQuoteLevelInRange:(struct _NSRange)arg1 by:(long long)arg2 undoManager:(id)arg3;	// IMP=0x0000000000084979
- (void)fixQuotingDisplayAttributesInRange:(struct _NSRange)arg1;	// IMP=0x000000000008421f
- (void)removeAllFormattingExceptAttachments;	// IMP=0x0000000000083e9d
- (void)removeAllAttachments;	// IMP=0x0000000000083e89
- (void)_removeAttachmentsAndReplaceWithCustomAttribute:(BOOL)arg1;	// IMP=0x0000000000083c53
@end

