//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSMutableDictionary (RFC2231Support)
- (void)fixupRFC2231ValuesWithSender:(id)arg1 fromWindows:(BOOL)arg2;	// IMP=0x000000000000b3c9
@end

