//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperationQueue.h>

@interface NSOperationQueue (MCTaskOperation)
- (void)addTaskOperation:(id)arg1 taskName:(id)arg2 priority:(unsigned char)arg3 canCancel:(BOOL)arg4;	// IMP=0x000000000001c206
@end

