//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScanner.h>

@interface NSScanner (MailCoreAdditions)
- (BOOL)scanUpAndOverString:(id)arg1;	// IMP=0x000000000008912a
- (id)nextTokenWithPunctuation:(id)arg1;	// IMP=0x0000000000088f32
@end

