//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSLock.h>

@interface _IMAPLock : NSLock
{
}

- (void)performBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000000005969a

@end

