//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/ECLocalActionReplayerDelegate-Protocol.h>

@class NSData, NSDictionary, NSError, NSIndexSet, NSString, NSURL;

@protocol ECIMAPLocalActionReplayerDelegate <ECLocalActionReplayerDelegate>
- (BOOL)errorIsIMAPError:(NSError *)arg1;
- (NSData *)messageDataForRemoteID:(NSString *)arg1 mailboxURL:(NSURL *)arg2;
- (BOOL)checkUIDValidity:(unsigned int)arg1 mailboxURL:(NSURL *)arg2;
- (NSDictionary *)flagsForIMAPUIDs:(NSIndexSet *)arg1 mailboxURL:(NSURL *)arg2;
- (NSString *)imapMailboxNameForMailboxURL:(NSURL *)arg1;
@end

