//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSCopying-Protocol.h>
#import <IMAP/NSObject-Protocol.h>

@class ACAccount, NSArray, NSString;

@protocol ECMailAccount <NSObject, NSCopying>
@property(readonly, copy) NSString *identifier;
@property(copy) NSString *password;
@property(copy) NSString *hostname;
@property(readonly, copy) NSArray *emailAddressStrings;
- (ACAccount *)systemAccount;
@end

