//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/ECMailAccount-Protocol.h>

@class NSString;

@protocol EDIndexableAccount <ECMailAccount>
+ (NSString *)csAccountTypeString;
@property(readonly, nonatomic, getter=isManaged) BOOL managed;
@end

