//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPFetchCommand.h>

@interface IMAPFetchUIDCommand : IMAPFetchCommand
{
}

- (BOOL)shouldSendAgainOnError;	// IMP=0x000000000002ee23
- (id)commandTypeString;	// IMP=0x000000000002ee04
- (BOOL)_isLegalRange:(CDStruct_f792af56)arg1;	// IMP=0x000000000002edd6

@end

