//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPPersistLabelChangesOperation, NSArray;

@protocol IMAPPersistLabelChangesOperationDelegate <NSObject>
- (void)persistLabelChangesOperation:(IMAPPersistLabelChangesOperation *)arg1 persistedLabelChangesForServerMessages:(NSArray *)arg2;
@end

