//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPResponse.h>

@class NSString;

@interface IMAPEnabledResponse : IMAPResponse
{
    NSString *_capability;	// 8 = 0x8
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x000000000002d660
@property(copy, nonatomic) NSString *capability; // @synthesize capability=_capability;
- (void).cxx_destruct;	// IMP=0x000000000002d75f
- (id)description;	// IMP=0x000000000002d68c

@end

