//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPPersistDeletedMessagesOperation, NSIndexSet;

@protocol IMAPPersistDeletedMessagesOperationDelegate <NSObject>
- (void)persistDeletedMessagesOperation:(IMAPPersistDeletedMessagesOperation *)arg1 deletedUIDs:(NSIndexSet *)arg2;
@end

