//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPMailboxCommand.h>

@interface IMAPDeleteCommand : IMAPMailboxCommand
{
}

- (id)activityString;	// IMP=0x0000000000036326
- (id)commandTypeString;	// IMP=0x0000000000036307

@end

