//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCTask.h>

@class NSString;

@interface IMAPTask : MCTask
{
    NSString *_mailboxName;	// 8 = 0x8
    long long _reservedNetworkPriority;	// 16 = 0x10
}

@property(nonatomic) long long reservedNetworkPriority; // @synthesize reservedNetworkPriority=_reservedNetworkPriority;
@property(copy, nonatomic) NSString *mailboxName; // @synthesize mailboxName=_mailboxName;
- (void).cxx_destruct;	// IMP=0x0000000000059687
- (void)operationFinished:(id)arg1;	// IMP=0x0000000000059541
- (void)trackOperation:(id)arg1;	// IMP=0x0000000000059445
- (BOOL)mailboxIsUserVisibleUsingDataSource:(id)arg1;	// IMP=0x0000000000059333
@property(readonly, copy, nonatomic) NSString *mailboxNameWithoutPII;
- (id)description;	// IMP=0x0000000000059236
- (id)init;	// IMP=0x0000000000059167
- (id)initWithMailboxName:(id)arg1;	// IMP=0x00000000000590ed

@end

