//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPSingleCommand.h>

@interface IMAPNoopCommand : IMAPSingleCommand
{
}

- (long long)maxAllowedConnectionState;	// IMP=0x000000000002343b
- (long long)minRequiredConnectionState;	// IMP=0x0000000000023430
- (BOOL)executeOnConnection:(id)arg1;	// IMP=0x0000000000023415
- (id)activityString;	// IMP=0x00000000000233a9
- (id)commandTypeString;	// IMP=0x000000000002338a

@end

