//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPBodyFetchResult.h>

@interface IMAPBodyTextFetchResult : IMAPBodyFetchResult
{
}

- (id)section;	// IMP=0x000000000001515e

@end

