//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPAggregateCommand.h>

@interface IMAPAggregateStatusCommand : IMAPAggregateCommand
{
}

- (long long)maxAllowedConnectionState;	// IMP=0x000000000003707e
- (long long)minRequiredConnectionState;	// IMP=0x0000000000037073
- (BOOL)executeOnConnection:(id)arg1;	// IMP=0x0000000000037058
- (id)activityString;	// IMP=0x0000000000036fec
- (id)commandTypeString;	// IMP=0x0000000000036fcd

@end

