//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPResponse.h>

@class NSArray;

@interface IMAPSearchResponse : IMAPResponse
{
    NSArray *_searchResults;	// 8 = 0x8
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x000000000000c66a
@property(copy, nonatomic) NSArray *searchResults; // @synthesize searchResults=_searchResults;
- (void).cxx_destruct;	// IMP=0x0000000000050f3d
- (id)description;	// IMP=0x0000000000050e9b
- (id)debugDescription;	// IMP=0x0000000000050dec

@end

