//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPSingleCommand.h>

@interface IMAPLogoutCommand : IMAPSingleCommand
{
}

- (long long)maxAllowedConnectionState;	// IMP=0x00000000000234f7
- (long long)minRequiredConnectionState;	// IMP=0x00000000000234ec
- (BOOL)executeOnConnection:(id)arg1;	// IMP=0x00000000000234d1
- (id)activityString;	// IMP=0x0000000000023465
- (id)commandTypeString;	// IMP=0x0000000000023446

@end

