//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPBasicResponse.h>

@interface IMAPBadResponse : IMAPBasicResponse
{
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x00000000000077ae
- (const char *)_responseName;	// IMP=0x0000000000019471
- (BOOL)descriptionIncludesUserString;	// IMP=0x0000000000019466

@end

