//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPVerifyMailboxOperation;

@protocol IMAPVerifyMailboxOperationDelegate <NSObject>
- (void)verifyMailboxOperation:(IMAPVerifyMailboxOperation *)arg1 foundInconsistencies:(BOOL)arg2;
@end

