//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPUIDCommand.h>

@interface IMAPUIDExpungeCommand : IMAPUIDCommand
{
}

- (BOOL)executeOnConnection:(id)arg1;	// IMP=0x0000000000069294
- (id)activityString;	// IMP=0x0000000000069227
- (id)commandTypeString;	// IMP=0x0000000000069208

@end

