//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPResponse.h>

@class NSDictionary;

@interface IMAPIDResponse : IMAPResponse
{
    NSDictionary *_serverID;	// 8 = 0x8
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x00000000000078b7
@property(copy, nonatomic) NSDictionary *serverID; // @synthesize serverID=_serverID;
- (void).cxx_destruct;	// IMP=0x0000000000007c78
- (id)description;	// IMP=0x000000000003324f

@end

