//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPPersistMessagesOperation, NSSet;

@protocol IMAPPersistMessagesOperationDelegate <NSObject>
- (void)persistMessagesOperation:(IMAPPersistMessagesOperation *)arg1 persistedMessages:(NSSet *)arg2 andGotNewMessages:(NSSet *)arg3;
@end

