//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPFetchDataItem.h>

@interface IMAPFetchChangedSinceDataItem : IMAPFetchDataItem
{
}

- (id)init;	// IMP=0x000000000002f55e
- (id)initWithModificationSequenceNumber:(unsigned long long)arg1 includeVanished:(BOOL)arg2;	// IMP=0x000000000002f4b3

@end

