//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPServerInterface, IMAPSyncSkeletonsOperation, NSArray;

@protocol IMAPSyncSkeletonsOperationDelegate <NSObject>
- (void)syncSkeletonsOperationFinished:(IMAPSyncSkeletonsOperation *)arg1 withFetchResponses:(NSArray *)arg2 serverInterface:(IMAPServerInterface *)arg3;
@end

