//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPUIDCommand.h>

@class NSArray, NSMutableIndexSet;

@interface IMAPUIDSearchCommand : IMAPUIDCommand
{
    NSArray *_terms;	// 40 = 0x28
    NSMutableIndexSet *_matchingUIDs;	// 48 = 0x30
}

@property(retain) NSMutableIndexSet *matchingUIDs; // @synthesize matchingUIDs=_matchingUIDs;
@property(copy) NSArray *terms; // @synthesize terms=_terms;
- (void).cxx_destruct;	// IMP=0x000000000006a951
- (BOOL)executeOnConnection:(id)arg1;	// IMP=0x000000000006a8e8
- (id)_newArgumentForSearchTerm:(id)arg1 isLiteral:(char *)arg2;	// IMP=0x000000000006a817
- (id)newCommandDataForLiteralPlus:(BOOL)arg1;	// IMP=0x000000000006a5a2
- (id)activityString;	// IMP=0x000000000006a535
- (id)commandTypeString;	// IMP=0x000000000006a516
- (id)debugCommandStringWithAccount:(id)arg1;	// IMP=0x000000000006a440
- (id)initWithMailboxName:(id)arg1 range:(CDStruct_f792af56)arg2;	// IMP=0x000000000006a371
- (id)initWithMailboxName:(id)arg1 UIDs:(id)arg2;	// IMP=0x000000000006a2a2
- (id)initWithMailboxName:(id)arg1 range:(CDStruct_f792af56)arg2 terms:(id)arg3;	// IMP=0x000000000006a1f2

@end

