//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPMailboxCommand.h>

@interface IMAPCreateCommand : IMAPMailboxCommand
{
}

- (id)activityString;	// IMP=0x000000000003629a
- (id)commandTypeString;	// IMP=0x000000000003627b

@end

