//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPPersistFlagChangesOperation, NSArray;

@protocol IMAPPersistFlagChangesOperationDelegate <NSObject>
- (void)persistFlagChangesOperation:(IMAPPersistFlagChangesOperation *)arg1 persistedFlagChangesForRemoteIDs:(NSArray *)arg2;
@end

