//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPFetchResult.h>

@interface IMAPUidFetchResult : IMAPFetchResult
{
    unsigned int _uid;	// 8 = 0x8
}

@property(nonatomic) unsigned int uid; // @synthesize uid=_uid;
- (id)description;	// IMP=0x00000000000311fd

@end

