//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPSyncBodiesOperation, NSOrderedSet, NSSet;

@protocol IMAPSyncBodiesOperationDelegate <NSObject>
- (void)syncBodiesOperation:(IMAPSyncBodiesOperation *)arg1 syncedBodiesForMessages:(NSOrderedSet *)arg2 downloadsToPersist:(NSOrderedSet *)arg3 messagesNeedingAttachments:(NSSet *)arg4;
@end

