//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPNetworkTaskOperation.h>

@interface IMAPNetworkBlockOperation : IMAPNetworkTaskOperation
{
    BOOL _blockCompleted;	// 8 = 0x8
    CDUnknownBlockType _block;	// 16 = 0x10
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic) BOOL blockCompleted; // @synthesize blockCompleted=_blockCompleted;
- (void).cxx_destruct;	// IMP=0x000000000004624a
- (void)main;	// IMP=0x00000000000460c5
- (id)initWithMailboxName:(id)arg1;	// IMP=0x0000000000045ff6
- (id)initWithBlock:(CDUnknownBlockType)arg1 mailboxName:(id)arg2;	// IMP=0x0000000000045f7a

@end

