//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPFetchResult.h>

@interface IMAPRFC822SizeFetchResult : IMAPFetchResult
{
    unsigned int _messageSize;	// 8 = 0x8
}

@property(nonatomic) unsigned int messageSize; // @synthesize messageSize=_messageSize;
- (id)description;	// IMP=0x0000000000031148

@end

