//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPSyncAttachmentsOperation, NSArray;

@protocol IMAPSyncAttachmentsOperationDelegate <NSObject>
- (void)syncAttachmentsOperation:(IMAPSyncAttachmentsOperation *)arg1 syncedAttachmentsForDownloads:(NSArray *)arg2;
@end

