//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPNumericResponse.h>

@interface IMAPExistsResponse : IMAPNumericResponse
{
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x000000000000ac94
- (const char *)_responseName;	// IMP=0x00000000000490ff

@end

