//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPBasicResponse.h>

@interface IMAPContinuationResponse : IMAPBasicResponse
{
}

- (BOOL)isUntagged;	// IMP=0x0000000000019451
- (const char *)_responseName;	// IMP=0x0000000000019444

@end

