//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPListCommand.h>

@interface IMAPLSubCommand : IMAPListCommand
{
}

- (id)activityString;	// IMP=0x0000000000033ab0
- (id)commandTypeString;	// IMP=0x0000000000033a91

@end

