//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCTaskHandlerOperation.h>

@protocol IMAPMessageDataSource;

@interface IMAPPersistenceTaskOperation : MCTaskHandlerOperation
{
    id <IMAPMessageDataSource> _dataSource;	// 8 = 0x8
}

@property(readonly, nonatomic) id <IMAPMessageDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;	// IMP=0x000000000004d964
- (id)_messagesForPersistentIDs:(id)arg1;	// IMP=0x000000000004d7a2
- (id)description;	// IMP=0x000000000004d6f3
- (id)init;	// IMP=0x000000000004d624
- (id)initWithDataSource:(id)arg1;	// IMP=0x000000000004d5b6

@end

