//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPSelectMailboxOperation, NSString;

@protocol IMAPSelectMailboxOperationDelegate <NSObject>
- (void)selectMailboxOperation:(IMAPSelectMailboxOperation *)arg1 selectedMailbox:(NSString *)arg2;
@end

