//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPMailboxCommand.h>

@interface IMAPSubscribeCommand : IMAPMailboxCommand
{
}

- (BOOL)executeOnConnection:(id)arg1;	// IMP=0x000000000003641e
- (id)activityString;	// IMP=0x00000000000363b2
- (id)commandTypeString;	// IMP=0x0000000000036393

@end

