//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPFetchResult.h>

@interface IMAPModificationSequenceFetchResult : IMAPFetchResult
{
    unsigned long long _modificationSequence;	// 8 = 0x8
}

@property(nonatomic) unsigned long long modificationSequence; // @synthesize modificationSequence=_modificationSequence;
- (id)description;	// IMP=0x00000000000312cf

@end

