//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPSyncUIDsFlagsAndLabelsOperation, NSArray, NSIndexSet;

@protocol IMAPSyncUIDsFlagsAndLabelsOperationDelegate <NSObject>
- (void)syncUIDsOperationFinished:(IMAPSyncUIDsFlagsAndLabelsOperation *)arg1 withFetchResponses:(NSArray *)arg2 vanishedUIDs:(NSIndexSet *)arg3;
@end

