//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPSelectCommand.h>

@interface IMAPExamineCommand : IMAPSelectCommand
{
}

- (BOOL)readOnly;	// IMP=0x0000000000036270
- (id)activityString;	// IMP=0x0000000000036203
- (id)commandTypeString;	// IMP=0x00000000000361e4

@end

