//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPBasicResponse.h>

@interface IMAPByeResponse : IMAPBasicResponse
{
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x0000000000007833
- (const char *)_responseName;	// IMP=0x00000000000194ae
- (BOOL)descriptionIncludesUserString;	// IMP=0x00000000000194a3

@end

