//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPAggregateCommand.h>

@interface IMAPAggregateGetQuotaRootCommand : IMAPAggregateCommand
{
}

- (long long)maxAllowedConnectionState;	// IMP=0x000000000004fe40
- (long long)minRequiredConnectionState;	// IMP=0x000000000004fe35
- (BOOL)shouldSendAgainOnError;	// IMP=0x000000000004fe2a
- (id)activityString;	// IMP=0x000000000004fdbe
- (id)commandTypeString;	// IMP=0x000000000004fd9f

@end

