//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPNumericResponse.h>

@interface IMAPExpungeResponse : IMAPNumericResponse
{
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x000000000000d8d9
- (const char *)_responseName;	// IMP=0x0000000000049119

@end

