//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPCommand.h>

@class NSArray;

@interface IMAPAggregateCommand : IMAPCommand
{
    NSArray *_commands;	// 16 = 0x10
}

@property(readonly, copy, nonatomic) NSArray *commands; // @synthesize commands=_commands;
- (void).cxx_destruct;	// IMP=0x0000000000022eec
- (void)cleanupAfterCompletion;	// IMP=0x0000000000022dac
- (long long)composition;	// IMP=0x0000000000022da1
- (id)init;	// IMP=0x0000000000022cd2
- (id)initWithCommands:(id)arg1;	// IMP=0x0000000000022c58

@end

