//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPGetMessagesOperation, NSArray;

@protocol IMAPGetMessagesOperationDelegate <NSObject>
- (void)getMessagesOperation:(IMAPGetMessagesOperation *)arg1 gotMessages:(NSArray *)arg2;
@end

