//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPBodyFetchResult.h>

@class NSString;

@interface IMAPBodySectionFetchResult : IMAPBodyFetchResult
{
    NSString *_section;	// 24 = 0x18
}

@property(copy, nonatomic) NSString *section; // @synthesize section=_section;
- (void).cxx_destruct;	// IMP=0x00000000000129ce

@end

