//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPSingleCommand.h>

@interface IMAPUnselectCommand : IMAPSingleCommand
{
}

- (long long)maxAllowedConnectionState;	// IMP=0x000000000002370b
- (long long)minRequiredConnectionState;	// IMP=0x0000000000023700
- (BOOL)executeOnConnection:(id)arg1;	// IMP=0x00000000000236e5
- (id)activityString;	// IMP=0x0000000000023679
- (id)commandTypeString;	// IMP=0x000000000002365a

@end

