//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPBodyFetchResult.h>

@interface IMAPBodyHeaderFetchResult : IMAPBodyFetchResult
{
}

- (id)section;	// IMP=0x00000000000129f1
- (BOOL)needsLineEndingConversion;	// IMP=0x000000000000efde

@end

