//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class ECLocalMessageActionResults, IMAPMessageActionSyncOperation;

@protocol IMAPMessageActionSyncOperationDelegate <NSObject>
- (void)messageActionSyncOperationCompleted:(IMAPMessageActionSyncOperation *)arg1 results:(ECLocalMessageActionResults *)arg2;
@end

