//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPUnselectCommand.h>

@interface IMAPCloseCommand : IMAPUnselectCommand
{
}

- (id)activityString;	// IMP=0x0000000000023735
- (id)commandTypeString;	// IMP=0x0000000000023716

@end

