//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPFetchResult.h>

@class NSArray;

@interface IMAPFlagsFetchResult : IMAPFetchResult
{
    NSArray *_flagsArray;	// 8 = 0x8
}

@property(copy, nonatomic) NSArray *flagsArray; // @synthesize flagsArray=_flagsArray;
- (void).cxx_destruct;	// IMP=0x000000000000eda3
- (id)description;	// IMP=0x000000000003123b
@property(readonly, nonatomic) long long messageFlags;

@end

