//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPResponse.h>

@interface IMAPNumericResponse : IMAPResponse
{
    unsigned long long _number;	// 8 = 0x8
}

@property(nonatomic) unsigned long long number; // @synthesize number=_number;
- (id)description;	// IMP=0x0000000000049025
- (const char *)_responseName;	// IMP=0x000000000004901d

@end

