//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPMailboxCommand.h>

@interface IMAPGetQuotaRootCommand : IMAPMailboxCommand
{
}

- (BOOL)shouldSendAgainOnError;	// IMP=0x000000000004fd94
- (id)activityString;	// IMP=0x000000000004fd28
- (id)commandTypeString;	// IMP=0x000000000004fd09

@end

