//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPGetNewLocalActionsOperation, NSArray;

@protocol IMAPGetNewLocalActionsOperationDelegate <NSObject>
- (void)getNewMessageActionsOperation:(IMAPGetNewLocalActionsOperation *)arg1 didGetActions:(NSArray *)arg2;
@end

