//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPPersistBodiesOperation, NSSet;

@protocol IMAPPersistBodiesOperationDelegate <NSObject>
- (void)persistBodiesOperation:(IMAPPersistBodiesOperation *)arg1 persistedDownloads:(NSSet *)arg2;
@end

