//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPListResponse.h>

@interface IMAPLSubResponse : IMAPListResponse
{
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x000000000000aa90
- (const char *)_responseName;	// IMP=0x0000000000033d4f

@end

