//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class NSString;

@protocol MCActivityTarget <NSObject>

@optional
@property(readonly, copy, nonatomic) NSString *displayName;
@end

