//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class NSArray;

@protocol MCBodyFetchContext <NSObject>
- (void)cacheBodiesForMessages:(NSArray *)arg1;
@end

