//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButton.h>

@interface _BaselinePopupButton : NSPopUpButton
{
}

- (struct NSEdgeInsets)alignmentRectInsets;	// IMP=0x000000010016786b

@end

