//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BasicComposeContext.h"

@interface _CompletionComposeContext : BasicComposeContext
{
    CDUnknownBlockType _loadCompletedHandler;	// 8 = 0x8
}

@property(copy, nonatomic) CDUnknownBlockType loadCompletedHandler; // @synthesize loadCompletedHandler=_loadCompletedHandler;
- (void).cxx_destruct;	// IMP=0x0000000100277df2
- (void)presentComposeViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100277dc8
- (void)loadCompleted:(id)arg1;	// IMP=0x0000000100277d34

@end

