//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface _ControllerTitleTransformer : NSValueTransformer
{
    BOOL _hasBeenEdited;	// 8 = 0x8
}

+ (BOOL)allowsReverseTransformation;	// IMP=0x00000001000ed248
@property(nonatomic) BOOL hasBeenEdited; // @synthesize hasBeenEdited=_hasBeenEdited;
- (id)transformedValue:(id)arg1;	// IMP=0x00000001000ed250

@end

