//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface _ConnectionURLTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;	// IMP=0x0000000100155a87
- (id)reverseTransformedValue:(id)arg1;	// IMP=0x0000000100155b11
- (id)transformedValue:(id)arg1;	// IMP=0x0000000100155aa0

@end

