//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface _FavoriteButtonCell : NSButtonCell
{
}

- (BOOL)_shouldDrawBezel;	// IMP=0x000000010001130a

@end

