//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface _FetchFrequencyTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;	// IMP=0x0000000100165a76
- (id)reverseTransformedValue:(id)arg1;	// IMP=0x0000000100165c08
- (id)transformedValue:(id)arg1;	// IMP=0x0000000100165a8f

@end

