//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

@interface _HyperlinkButton : NSButton
{
}

- (void)resetCursorRects;	// IMP=0x000000010016e72f

@end

