//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MFMailbox;

@interface _MailboxAlertRecord : NSObject
{
    BOOL _userInitiated;	// 8 = 0x8
    MFMailbox *_mailbox;	// 16 = 0x10
}

@property(readonly, nonatomic) BOOL userInitiated; // @synthesize userInitiated=_userInitiated;
@property(readonly, nonatomic) MFMailbox *mailbox; // @synthesize mailbox=_mailbox;
- (void).cxx_destruct;	// IMP=0x000000010022096b
- (id)description;	// IMP=0x0000000100220883
- (id)init;	// IMP=0x00000001002207b4
- (id)initWithMailbox:(id)arg1 userInitiated:(BOOL)arg2;	// IMP=0x000000010022073e

@end

