//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSegmentedControl.h>

@class MFMailbox;

@interface _MailboxSegmentedControl : NSSegmentedControl
{
    BOOL _useAsBackNavigation;	// 108 = 0x6c
    MFMailbox *_mailbox;	// 112 = 0x70
}

@property(nonatomic) BOOL useAsBackNavigation; // @synthesize useAsBackNavigation=_useAsBackNavigation;
@property(retain, nonatomic) MFMailbox *mailbox; // @synthesize mailbox=_mailbox;
- (void).cxx_destruct;	// IMP=0x00000001002209c1

@end

