//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageView.h>

@interface _MessageAttachmentViewImageView : NSImageView
{
}

- (id)menuForEvent:(id)arg1;	// IMP=0x00000001000b9b6f
- (void)setImage:(id)arg1;	// IMP=0x00000001000b9aff

@end

