//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTMSpecialMailbox.h"

@interface _MTMJunkMailbox : MTMSpecialMailbox
{
}

- (BOOL)enabled;	// IMP=0x000000010023dc01
- (id)defaultMessageColumnAttributesKey;	// IMP=0x000000010023dbe2
- (id)displayName;	// IMP=0x000000010023db75

@end

