//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_MTMStoredMetaMailbox.h"

@interface _MTMDraftsMailbox : _MTMStoredMetaMailbox
{
}

- (id)severalMessagesFormatString;	// IMP=0x000000010023d802
- (id)oneMessageFormatString;	// IMP=0x000000010023d799
- (id)defaultMessageColumnAttributesKey;	// IMP=0x000000010023d77a
- (id)messageColumnConfiguration;	// IMP=0x000000010023d75b
- (id)restoreMode;	// IMP=0x000000010023d747
- (id)recoverDisplayName;	// IMP=0x000000010023d6da
- (id)displayName;	// IMP=0x000000010023d66d

@end

