//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_MTMMetaMailbox.h"

@interface _MTMArchiveMailbox : _MTMMetaMailbox
{
}

- (id)defaultMessageColumnAttributesKey;	// IMP=0x000000010023db56
- (id)recoverDisplayName;	// IMP=0x000000010023dae9
- (id)displayName;	// IMP=0x000000010023da7c

@end

