//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_MTMSubMetaMailbox.h"

@interface _MTMDisabledSubMetaMailbox : _MTMSubMetaMailbox
{
}

- (BOOL)enabled;	// IMP=0x000000010023ce2c

@end

