//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTMSpecialMailbox.h"

@interface _MTMStoredMetaMailbox : MTMSpecialMailbox
{
}

- (BOOL)_shouldSortMailboxes;	// IMP=0x000000010023c857
- (id)restoreString;	// IMP=0x000000010023c780
- (id)paths;	// IMP=0x000000010023c5d6
- (void)loadNextMessagesWithControllingMailbox:(id)arg1 andFetcher:(id)arg2;	// IMP=0x000000010023c267
- (void)_updateMessages:(id)arg1;	// IMP=0x000000010023c0e9
- (void)_loadMessages;	// IMP=0x000000010023be58

@end

