//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTMSpecialMailbox.h"

@interface _MTMAccountMailbox : MTMSpecialMailbox
{
}

- (id)identifier;	// IMP=0x000000010023b187
- (id)subRestoreString;	// IMP=0x000000010023ac9c
- (id)restoreString;	// IMP=0x000000010023abc5
- (id)recoverDisplayName;	// IMP=0x000000010023aafb
- (id)displayName;	// IMP=0x000000010023aaab

@end

