//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTMSpecialMailbox.h"

@interface _MTMRootMailbox : MTMSpecialMailbox
{
}

- (BOOL)_shouldSortMailboxes;	// IMP=0x000000010023aaa0
- (id)messages;	// IMP=0x000000010023aa98

@end

