//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTMSpecialMailbox.h"

@interface _MTMSectionMailbox : MTMSpecialMailbox
{
}

- (BOOL)canCollapse;	// IMP=0x000000010023dd06
- (id)displayName;	// IMP=0x000000010023dc4d

@end

