//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_MTMMetaMailbox.h"

@interface _MTMTrashMailbox : _MTMMetaMailbox
{
}

- (id)defaultMessageColumnAttributesKey;	// IMP=0x000000010023da5d
- (id)recoverDisplayName;	// IMP=0x000000010023d9f0
- (id)displayName;	// IMP=0x000000010023d983

@end

