//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTMSpecialMailbox.h"

@interface _MTMSmartMailbox : MTMSpecialMailbox
{
}

- (BOOL)isSpotlightMailbox;	// IMP=0x000000010023dc42
- (BOOL)enabled;	// IMP=0x000000010023dc3a
- (id)messageColumnConfiguration;	// IMP=0x000000010023dc1b
- (id)identifier;	// IMP=0x000000010023dc09

@end

