//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_MTMSubMetaMailbox.h"

@interface _MTMStoredSubMetaMailbox : _MTMSubMetaMailbox
{
}

- (void)loadNextMessagesWithControllingMailbox:(id)arg1 andFetcher:(id)arg2;	// IMP=0x000000010023d12e
- (void)_updateMessages:(id)arg1;	// IMP=0x000000010023d0c5
- (void)_loadMessages;	// IMP=0x000000010023ce34

@end

