//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextAttachmentCell.h>

@interface _PaddedTextAttachmentCell : NSTextAttachmentCell
{
    double _baselineOffset;	// 24 = 0x18
}

@property(nonatomic) double baselineOffset; // @synthesize baselineOffset=_baselineOffset;
- (struct CGPoint)cellBaselineOffset;	// IMP=0x000000010016e871
- (struct CGSize)cellSize;	// IMP=0x000000010016e82b
- (id)init;	// IMP=0x000000010016e7d7

@end

