//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface _RelatedMessageBannerView : NSView
{
}

- (void)updateLayer;	// IMP=0x00000001002053a6

@end

