//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButtonCell.h>

@interface _RolloverPopUpButtonCell : NSPopUpButtonCell
{
}

- (struct CGRect)_indicatorFrameForCellFrame:(struct CGRect)arg1 inView:(id)arg2;	// IMP=0x0000000100267d65
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;	// IMP=0x0000000100267c27
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;	// IMP=0x0000000100267b53

@end

