//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSVisualEffectView.h>

@class SGBanner;

@interface _SuggestionsBannerView : NSVisualEffectView
{
    SGBanner *_banner;	// 112 = 0x70
}

@property(retain, nonatomic) SGBanner *banner; // @synthesize banner=_banner;
- (void).cxx_destruct;	// IMP=0x00000001002965e3
- (void)awakeFromNib;	// IMP=0x000000010029651b

@end

