//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BasicComposeContext.h"

@interface _UserActivityComposeContext : BasicComposeContext
{
}

- (void)loadCompleted:(id)arg1;	// IMP=0x00000001002ad02a
- (id)initWithMessage:(id)arg1;	// IMP=0x00000001002acfa0

@end

