//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/_WKAttachment.h>

@class AttachmentViewController;

@interface _WKAttachment (MailAdditions)
@property(nonatomic, setter=mail_setViewController:) AttachmentViewController *mail_viewController;
@end

