//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface AccountSetupManager : NSObject
{
}

+ (void)showAddAccountSheetInWindow:(id)arg1 cancelWillQuit:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000a4b09

@end

