//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AccountInfo, NSView;

@protocol AccountInfoTabOwner <NSObject>
@property(readonly, nonatomic) NSView *view;
- (void)accountInfoWillShowView:(AccountInfo *)arg1;
- (void)accountInfoWillHideView:(AccountInfo *)arg1;
@end

