//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@interface ActivityWindowCellView : NSTableCellView
{
}

+ (id)keyPathsForValuesAffectingShouldShowSuspendedReason;	// IMP=0x00000001000a6fb9
+ (id)keyPathsForValuesAffectingShouldShowOverrideButton;	// IMP=0x00000001000a6f2c
@property(readonly, nonatomic) BOOL shouldShowSuspendedReason;
@property(readonly, nonatomic) BOOL shouldShowOverrideButton;

@end

