//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ACAccount, NSString;

@protocol ACUIAccountsTableViewControllerDelegate <NSObject>
- (void)didSelectAccount:(ACAccount *)arg1;

@optional
- (NSString *)subTitleOverrideForAccount:(ACAccount *)arg1;
- (void)didRefreshAccounts;
@end

