//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class Assistant;

@protocol AssistantDelegate <NSObject>
- (void)assistantDidFinish:(Assistant *)arg1;
@end

