//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AttachmentViewController, NSString;

@protocol AttachmentManagerDelegate <NSObject>
- (NSString *)directoryForAttachment:(AttachmentViewController *)arg1;
@end

