//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface AuthSchemeValueTransformer : NSValueTransformer
{
}

+ (BOOL)allowsReverseTransformation;	// IMP=0x00000001000975a3
+ (Class)transformedValueClass;	// IMP=0x000000010009758a
- (id)reverseTransformedValue:(id)arg1;	// IMP=0x0000000100097649
- (id)transformedValue:(id)arg1;	// IMP=0x00000001000975ae

@end

