//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

#import "NSAccessibilityGroup-Protocol.h"

@class NSColor, NSString;

@interface BannerBackgroundView : NSView <NSAccessibilityGroup>
{
    NSColor *_bannerColor;	// 112 = 0x70
}

@property(retain, nonatomic) NSColor *bannerColor; // @synthesize bannerColor=_bannerColor;
- (void).cxx_destruct;	// IMP=0x00000001000c55cf
- (void)updateLayer;	// IMP=0x00000001000860ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

