//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CalendarBannerIconCreator : NSObject
{
}

+ (id)newCalendarBannerIconForDate:(id)arg1;	// IMP=0x00000001000c9c0f
+ (void)drawBackgroundTileInRect:(struct CGRect)arg1 pathToBackground:(id)arg2 date:(id)arg3;	// IMP=0x00000001000c979b
+ (id)monthStringAttributes;	// IMP=0x00000001000c9652
+ (id)dateStringAttributes;	// IMP=0x00000001000c94f6

@end

