//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CNContact, CNContactPicker, CNContactProperty;

@protocol CNContactPickerDelegate <NSObject>

@optional
- (void)contactPickerDidClose:(CNContactPicker *)arg1;
- (void)contactPickerWillClose:(CNContactPicker *)arg1;
- (void)contactPicker:(CNContactPicker *)arg1 didSelectContactProperty:(CNContactProperty *)arg2;
- (void)contactPicker:(CNContactPicker *)arg1 didSelectContact:(CNContact *)arg2;
@end

