//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSVisualEffectView.h>

@interface ComposeHeaderRowView : NSVisualEffectView
{
}

- (void)awakeFromNib;	// IMP=0x00000001000e95cc

@end

