//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TypeAheadWindow.h"

@class NSResponder;

@interface ComposeWindow : TypeAheadWindow
{
    BOOL _disableFrameConstraint;	// 92 = 0x5c
    NSResponder *_nextFirstResponder;	// 96 = 0x60
}

@property(nonatomic) BOOL disableFrameConstraint; // @synthesize disableFrameConstraint=_disableFrameConstraint;
@property(retain, nonatomic) NSResponder *nextFirstResponder; // @synthesize nextFirstResponder=_nextFirstResponder;
- (void).cxx_destruct;	// IMP=0x0000000100107ff0
- (struct CGRect)constrainFrameRect:(struct CGRect)arg1 toScreen:(id)arg2;	// IMP=0x0000000100107edd
- (BOOL)makeFirstResponder:(id)arg1;	// IMP=0x0000000100107e2e

@end

