//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ComposeViewController, NSToolbarItem;
@protocol PopoutAnimationContentProvider;

@protocol ComposeViewControllerDelegate <NSObject>
@property(nonatomic) BOOL shouldCloseWindowWhenAnimationCompletes;
- (id <PopoutAnimationContentProvider>)animationContentProvider:(ComposeViewController *)arg1;
- (void)synchronizeIncludeAttachmentsToolbarItem:(NSToolbarItem *)arg1;
- (void)synchronizeToolbarReplyWithType:(long long)arg1;
- (void)composeViewControllerDidFinishLoading:(ComposeViewController *)arg1;
- (void)composeViewControllerShouldShow:(ComposeViewController *)arg1;
- (void)composeViewControllerShouldClose:(ComposeViewController *)arg1;
- (void)composeViewControllerDidSend:(ComposeViewController *)arg1;
- (void)prepareComposeViewController:(ComposeViewController *)arg1 forSendingWithCompletionHandler:(void (^)(void))arg2;
- (void)updateSendButtonStateInToolbar;
@end

