//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextView.h>

@interface ContentHuggingTextView : NSTextView
{
}

- (struct CGSize)intrinsicContentSize;	// IMP=0x000000010012ba6f

@end

