//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface CriteriaDocumentView : NSView
{
}

- (BOOL)isFlipped;	// IMP=0x000000010011bcc4

@end

