//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableView.h>

@interface DeletingTableView : NSTableView
{
}

- (void)keyDown:(id)arg1;	// IMP=0x0000000100273623

@end

