//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/DOMCSSValue.h>

@interface DOMCSSValue (MailExtras)
- (BOOL)matchesFontFamily:(id)arg1;	// IMP=0x000000010013754c
@end

