//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/DOMDocumentFragment.h>

@interface DOMDocumentFragment (MailExtras)
- (void)insertTextAtBeginning:(id)arg1 atEnd:(id)arg2;	// IMP=0x00000001001383c5
@property(readonly, nonatomic) DOMDocumentFragment *unwrappedFragment;
@end

