//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/DOMDocument.h>

@interface DOMDocument (MailExtras)
- (id)createBlockPlaceholder;	// IMP=0x0000000100137501
@end

