//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/DOMElement.h>

@interface DOMElement (MailHTMLAttachments)
- (BOOL)getNewElement:(id *)arg1 usingAttachments:(id)arg2 excludeRemoteImages:(BOOL)arg3;	// IMP=0x00000001000c4bd4
- (void)scrollToBottom;	// IMP=0x00000001001374d1
@property(readonly, nonatomic) BOOL hasMarginsOfZero;
- (BOOL)isBlockLevelElement;	// IMP=0x00000001001372ed
@end

