//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/DOMHTMLImageElement.h>

@interface DOMHTMLImageElement (MailHTMLAttachments)
- (BOOL)getNewElement:(id *)arg1 usingAttachments:(id)arg2 excludeRemoteImages:(BOOL)arg3;	// IMP=0x00000001000c4bdc
@end

