//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/DOMHTMLObjectElement.h>

@interface DOMHTMLObjectElement (AttachmentLocator)
- (void)attachment:(id *)arg1 url:(id *)arg2 fromDocument:(id)arg3;	// IMP=0x0000000100138187
@end

