//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/DOMHTMLElement.h>

@interface DOMHTMLElement (MailQuoteLevel)
+ (BOOL)isRichTextStyle:(id)arg1;	// IMP=0x000000010005f96c
+ (BOOL)isRichTextStyleCheckingOnlyFont:(id)arg1;	// IMP=0x000000010005f9cd
+ (BOOL)isRichTextStyleNotCheckingFont:(id)arg1;	// IMP=0x000000010005fb36
- (long long)quoteLevelDelta;	// IMP=0x0000000100060e35
- (BOOL)hasClassName:(id)arg1;	// IMP=0x0000000100137e93
- (void)attachment:(id *)arg1 url:(id *)arg2 fromDocument:(id)arg3;	// IMP=0x0000000100076022
- (void)restoreEditableElementsEdited:(id *)arg1 unedited:(id *)arg2;	// IMP=0x0000000100137db9
- (void)recursivelyRemoveMailAttributes:(BOOL)arg1 convertObjectsToImages:(BOOL)arg2 convertEditableElements:(BOOL)arg3 removeDefaultColorStyle:(BOOL)arg4;	// IMP=0x0000000100056596
- (BOOL)isRichTextElementForMessageFont:(id)arg1;	// IMP=0x00000001000603f4
@property(readonly, nonatomic) BOOL isRichTextElementType;
@end

