//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "EditingWebMessageController.h"

@class WKWebView;

@interface EditingWebMessageControllerWK2 : EditingWebMessageController
{
}

- (void)dealloc;	// IMP=0x000000010014f885
@property(retain, nonatomic) WKWebView *webView;

@end

