//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class EditingWebMessageController, NSURL;

@protocol EditingWebMessageControllerDelegate <NSObject>
- (void)editingWebMessageController:(EditingWebMessageController *)arg1 addFileWithURL:(NSURL *)arg2;
@end

