//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface EncryptToolTipValueTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;	// IMP=0x00000001001677c7
- (id)transformedValue:(id)arg1;	// IMP=0x00000001001677e0

@end

