//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AccountInformationController.h"

@class NSNumber;

@interface EWSIMAPAccountInformationController : AccountInformationController
{
}

+ (id)keyPathsForValuesAffectingAccountCachePolicy;	// IMP=0x0000000100155050
+ (id)keyPathsForValuesAffectingAccountUsesMailDrop;	// IMP=0x0000000100154f42
@property(nonatomic) long long accountCachePolicy;
@property(retain, nonatomic) NSNumber *accountUsesMailDrop;

@end

