//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RemoteStoreQuota.h"

@class MFEWSSizeEngine;

@interface EWSQuota : RemoteStoreQuota
{
}

- (void)_updateUsageField;	// IMP=0x00000001001555d1
- (void)engineUpdated:(id)arg1;	// IMP=0x00000001001554d7
- (void)engineDidFinish;	// IMP=0x000000010015545a
- (void)engineDidStart;	// IMP=0x00000001001553eb
- (id)initWithSizeEngine:(id)arg1;	// IMP=0x0000000100155236

// Remaining properties
@property(readonly, nonatomic) MFEWSSizeEngine *sizeEngine; // @dynamic sizeEngine;

@end

