//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScriptCommand.h>

@interface ExtractAddressCommand : NSScriptCommand
{
}

- (id)performDefaultImplementation;	// IMP=0x00000001001a1df9
- (id)executeCommand;	// IMP=0x00000001001a1cdd
- (id)_getRawAddressForObject:(id)arg1;	// IMP=0x00000001001a1bd2

@end

