//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScriptCommand.h>

@interface ExtractNameCommand : NSScriptCommand
{
}

- (id)performDefaultImplementation;	// IMP=0x00000001001a207f
- (id)executeCommand;	// IMP=0x00000001001a1f63
- (id)_getAddressDisplayNameForObject:(id)arg1;	// IMP=0x00000001001a1e58

@end

