//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MFMailbox;
@protocol MFUIMailbox;

@protocol FavoritesMenuDelegateProtocol <NSObject>

@optional
@property(readonly, nonatomic) id <MFUIMailbox> selectedMailbox;
- (void)menuDidClose;
- (void)menuDidPresent;
- (void)menuDidSelectMailbox:(MFMailbox *)arg1;
@end

