//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "EmailImporter.h"

@class NSSet;

@interface FilesystemEmailImporter : EmailImporter
{
}

- (BOOL)isValidMailbox:(id)arg1;	// IMP=0x0000000100160fe2
@property(readonly, copy, nonatomic) NSSet *pathExtensions;
- (void)readMailbox:(id)arg1 intoMailbox:(id)arg2;	// IMP=0x0000000100160d63
- (void)processUserSelection;	// IMP=0x0000000100160638
- (void)prepareForImport;	// IMP=0x00000001001605e7

@end

