//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FlaggedStatusToolbarItem;

@protocol FlaggedStatusToolbarItemDelegate <NSObject>

@optional
- (void)toggleFlaggedStatus:(BOOL)arg1;
- (BOOL)validateFlaggedStatusToolbarItem:(FlaggedStatusToolbarItem *)arg1;
@end

