//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageView.h>

@interface FlagButtonImageView : NSImageView
{
    BOOL _selected;	// 108 = 0x6c
    BOOL _displayMouseOverStyle;	// 109 = 0x6d
}

@property(nonatomic) BOOL displayMouseOverStyle; // @synthesize displayMouseOverStyle=_displayMouseOverStyle;
@property(nonatomic) BOOL selected; // @synthesize selected=_selected;
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x000000010008f02d

@end

