//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSVisualEffectView.h>

#import "NSAccessibilityGroup-Protocol.h"

@class NSString;

@interface HeaderView : NSVisualEffectView <NSAccessibilityGroup>
{
}

- (void)awakeFromNib;	// IMP=0x000000010016e8ee
- (BOOL)isFlipped;	// IMP=0x00000001000373c2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

