//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextAttachmentCell.h>

@interface HeaderTruncationAttachmentCell : NSTextAttachmentCell
{
    unsigned long long _truncatedRecipients;	// 24 = 0x18
    BOOL _truncatesAllRecipients;	// 32 = 0x20
    BOOL _showWithNoTruncation;	// 33 = 0x21
    double _fontSize;	// 40 = 0x28
}

@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
- (void)_updateTitle;	// IMP=0x000000010016e600
@property(nonatomic) BOOL showWithNoTruncation;
@property(nonatomic) BOOL truncatesAllRecipients;
@property(nonatomic) unsigned long long truncatedRecipients;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;	// IMP=0x000000010003f7bb
- (struct CGRect)cellFrameForTextContainer:(id)arg1 proposedLineFragment:(struct CGRect)arg2 glyphPosition:(struct CGPoint)arg3 characterIndex:(unsigned long long)arg4;	// IMP=0x000000010003f50e
- (struct CGSize)cellSizeForBounds:(struct CGRect)arg1;	// IMP=0x000000010003f76c
- (struct CGSize)cellSize;	// IMP=0x000000010016e520
- (struct CGPoint)cellBaselineOffset;	// IMP=0x000000010003f579
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;	// IMP=0x000000010003f5d7
- (id)_textAttributes;	// IMP=0x000000010003f683
- (id)init;	// IMP=0x000000010016e4bf

@end

