//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class EditingMessageWebView;

@protocol HyperlinkEditorDelegate <NSObject>
- (void)webViewDidInsertRichText:(EditingMessageWebView *)arg1;
@end

