//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ImageConverter;

@protocol ImageConverterDelegate <NSObject>
- (void)imageConverter:(ImageConverter *)arg1 didFinishConversionWithResultCode:(long long)arg2;
@end

