//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AdvancedServerSettingsController.h"

@class NSString;

@interface IMAPAdvancedServerSettingsController : AdvancedServerSettingsController
{
    BOOL _accountNeedsSaving;	// 16 = 0x10
}

+ (id)keyPathsForValuesAffectingServerPath;	// IMP=0x000000010017bd69
@property(nonatomic) BOOL accountNeedsSaving; // @synthesize accountNeedsSaving=_accountNeedsSaving;
@property(copy, nonatomic) NSString *serverPath;

@end

