//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TemporaryAttachmentOpener.h"

@interface InvitationAttachmentOpener : TemporaryAttachmentOpener
{
    BOOL _openImmediately;	// 8 = 0x8
}

@property(readonly, nonatomic) BOOL openImmediately; // @synthesize openImmediately=_openImmediately;
- (void)beginSaveOfAttachments:(id)arg1 toTemporaryFolderWithName:(id)arg2 taskName:(id)arg3;	// IMP=0x000000010018da2b
- (void)_saveAttachmentsToICalCaches:(id)arg1;	// IMP=0x000000010018d11d
- (id)initWithAttachmentViewControllers:(id)arg1 applicationPath:(id)arg2;	// IMP=0x000000010018d04e
- (id)initWithAttachmentViewControllers:(id)arg1 openImmediately:(BOOL)arg2;	// IMP=0x000000010018cf79

@end

