//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSegmentedCell.h>

@class NSMutableDictionary;

@interface LazyMenuSegmentedCell : NSSegmentedCell
{
    NSMutableDictionary *_loadedMenus;	// 24 = 0x18
    CDUnknownBlockType _lazyMenuBlock;	// 32 = 0x20
}

@property(copy, nonatomic) CDUnknownBlockType lazyMenuBlock; // @synthesize lazyMenuBlock=_lazyMenuBlock;
- (void).cxx_destruct;	// IMP=0x00000001001c263f
- (id)menuForSegment:(long long)arg1;	// IMP=0x00000001000467ff
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001c2590

@end

