//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSMenuItem.h>

@class NSMenu;

@interface LazySubmenuMenuItem : NSMenuItem
{
    BOOL _enableLoadedSubmenu;	// 8 = 0x8
    CDUnknownBlockType _lazySubmenuBlock;	// 16 = 0x10
    NSMenu *_loadedSubmenu;	// 24 = 0x18
}

@property(nonatomic) BOOL enableLoadedSubmenu; // @synthesize enableLoadedSubmenu=_enableLoadedSubmenu;
@property(retain, nonatomic) NSMenu *loadedSubmenu; // @synthesize loadedSubmenu=_loadedSubmenu;
@property(copy, nonatomic) CDUnknownBlockType lazySubmenuBlock; // @synthesize lazySubmenuBlock=_lazySubmenuBlock;
- (void).cxx_destruct;	// IMP=0x00000001001c2ae8
- (void)setEnabled:(BOOL)arg1;	// IMP=0x00000001001c29cc
- (BOOL)isEnabled;	// IMP=0x00000001001c2917
- (id)submenu;	// IMP=0x00000001001c276d
- (BOOL)hasSubmenu;	// IMP=0x00000001001c270d
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001c2670

@end

