//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTabViewController.h>

@interface MailTabViewController : NSTabViewController
{
}

- (void)viewDidLoad;	// IMP=0x00000001001cd03b

@end

