//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScriptCommand.h>

@interface MailToCommand : NSScriptCommand
{
}

- (id)performDefaultImplementation;	// IMP=0x00000001001a1ab3

@end

