//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class ActivityViewController, MailboxesOutlineViewController;

@interface MailboxesViewController : NSViewController
{
    MailboxesOutlineViewController *_outlineViewController;	// 16 = 0x10
    ActivityViewController *_activityViewController;	// 24 = 0x18
}

@property(retain, nonatomic) ActivityViewController *activityViewController; // @synthesize activityViewController=_activityViewController;
@property(retain, nonatomic) MailboxesOutlineViewController *outlineViewController; // @synthesize outlineViewController=_outlineViewController;
- (void).cxx_destruct;	// IMP=0x00000001001ba76a

@end

