//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMoveCommand.h>

@interface MailMoveCommand : NSMoveCommand
{
}

+ (void)_performBackgroundCommand:(id)arg1 copyMessages:(id)arg2 fromStores:(id)arg3 toMailbox:(id)arg4 shouldDelete:(BOOL)arg5;	// IMP=0x0000000100127046
- (id)performDefaultImplementation;	// IMP=0x000000010012758d

@end

