//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSInspectorBar.h>

@interface MailInspectorBar : NSInspectorBar
{
}

+ (id)standardTextItemIdentifiers;	// IMP=0x00000001001c10dc
+ (Class)standardItemControllerClass;	// IMP=0x00000001001c10c3
- (long long)_defaultItemGravity;	// IMP=0x00000001001c12ac
- (void)inspectorBarViewDidLoad:(id)arg1;	// IMP=0x00000001001c120d

@end

