//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSTextFieldDelegate-Protocol.h"

@protocol MailboxTextFieldDelegate <NSTextFieldDelegate>

@optional
- (void)mailboxTextFieldEndedEditingSession;
- (void)mailboxTextFieldBeganEditingSession;
@end

