//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSOutlineViewDelegate-Protocol.h"

@class MailboxesOutlineView;

@protocol MailboxesOutlineViewDelegate <NSOutlineViewDelegate>

@optional
- (void)outlineViewDidReload:(MailboxesOutlineView *)arg1;
- (void)setFirstResponderAfterMouseDownOnOutlineView:(MailboxesOutlineView *)arg1;
- (void)selectAllInOutlineView:(MailboxesOutlineView *)arg1;
@end

