//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MFMailbox, NSArray, NSMenu, NSString, NSWindow;

@protocol MailboxSelectionOwner <NSObject>
@property(readonly, nonatomic) NSWindow *mailboxSelectionWindow;
@property(readonly, nonatomic) BOOL isSelectedMailboxSpecial;
@property(readonly, copy, nonatomic) NSArray *sortedSectionItemsForTimeMachine;
@property(readonly, nonatomic) MFMailbox *selectedMailbox;
@property(readonly, copy, nonatomic) NSArray *selectedMailboxes;
- (void)revealMailbox:(MFMailbox *)arg1;
- (BOOL)sectionIsExpanded:(NSString *)arg1;
- (BOOL)mailboxIsExpanded:(MFMailbox *)arg1;
- (void)selectPathsToMailboxes:(NSArray *)arg1;

@optional
@property(readonly, copy, nonatomic) NSArray *expandedItems;
- (void)didCloseContextMenu:(NSMenu *)arg1;
- (void)willShowContextMenu:(NSMenu *)arg1;
@end

