//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MFMailbox, NSString;

@protocol MailboxOutlineItemControllerDelegate <NSObject>
- (void)mailbox:(MFMailbox *)arg1 nameUpdated:(NSString *)arg2;
- (unsigned long long)badgeCountForItem:(id)arg1;
@end

