//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface MailboxBadgeCell : NSButtonCell
{
}

- (id)accessibilityRoleDescription;	// IMP=0x00000001001a9eb5
- (struct CGSize)cellSizeForBounds:(struct CGRect)arg1;	// IMP=0x0000000100018e70

@end

