//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

@interface MailboxBadgeView : NSButton
{
}

+ (Class)cellClass;	// IMP=0x00000001000161e7
- (BOOL)shouldSetFontSmoothingBackgroundColor;	// IMP=0x00000001001a9f69
- (id)hitTest:(struct CGPoint)arg1;	// IMP=0x000000010004a59b
- (void)_mailboxBadgeViewCommonInit;	// IMP=0x0000000100016200
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100016188
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001a9f22

@end

