//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray;

@protocol MailboxesOutlineViewControllerDelegate <NSObject>
@property(readonly, nonatomic) long long viewerNumber;
- (void)focusMessages;
- (void)selectAllMessages;

@optional
- (void)mailboxSelectionChanged:(NSArray *)arg1;
@end

