//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MailboxOutlineItemView, NSImage;

@protocol MailboxOutlineItemViewDelegate <NSObject>
- (NSImage *)mailboxOutlineItemViewShouldDisplayImage:(MailboxOutlineItemView *)arg1;
@end

