//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDeleteCommand.h>

@interface MailDeleteCommand : NSDeleteCommand
{
}

- (id)performDefaultImplementation;	// IMP=0x0000000100127aef

@end

