//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray;

@protocol ManagedListSortInfo <NSObject>
- (void)unregisterSortInfoForObject:(id)arg1;
- (void)registerSortInfoForObjects:(NSArray *)arg1;
- (void)registerSortInfoForObject:(id)arg1;
@end

