//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FilesystemEmailImporter.h"

@interface MboxEmailImporter : FilesystemEmailImporter
{
}

+ (id)explanatoryText;	// IMP=0x00000001001d62d3
+ (id)name;	// IMP=0x00000001001d62b4
- (void)prepareForImport;	// IMP=0x00000001001d6340

@end

