//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCAttachment.h>

@interface MCAttachment (MailAdditions)
- (id)initWithWebResource:(id)arg1;	// IMP=0x00000001001c2b19
@end

