//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, NSURL;

@protocol MCCIDURLProtocolDataProvider <NSObject>
@property(readonly, copy) NSString *mimeType;
@property(readonly) NSURL *cidURL;
- (void)dataWithCompletionBlock:(void (^)(NSData *, NSError *))arg1;

@optional
@property(readonly) long long fileSize;
@end

