//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCMessage.h>

@interface MCMessage (MailViewerAdditions)
- (void)handleBounceMessage:(id)arg1;	// IMP=0x00000001001d875d
- (id)handleRedirectMessage:(id)arg1;	// IMP=0x00000001001d8617
- (id)handleForwardMessage:(id)arg1;	// IMP=0x00000001001d84d1
- (id)handleReplyToMessage:(id)arg1;	// IMP=0x00000001001d8338
- (void)handleOpenAppleEvent:(id)arg1;	// IMP=0x00000001001d8212
@end

