//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MessageFilterSelectorViewController;

@protocol MessageFilterSelectorViewControllerDelegate <NSObject>
- (void)messageFilterSelectorViewControllerDidChangeSelection:(MessageFilterSelectorViewController *)arg1;
@end

