//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableRowView.h>

@interface MessageFilterSelectorRowView : NSTableRowView
{
}

- (void)didAddSubview:(id)arg1;	// IMP=0x00000001001d895f
- (void)setSelected:(BOOL)arg1;	// IMP=0x00000001001d8784

@end

