//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSClipView.h>

@interface MessageBodyClipView : NSClipView
{
    double _oldDocumentWidth;	// 152 = 0x98
}

- (void)viewFrameChanged:(id)arg1;	// IMP=0x00000001001d6548
- (void)setFrameSize:(struct CGSize)arg1;	// IMP=0x00000001001d6394

@end

