//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableHeaderCell.h>

@class MessageListCell;

@interface MessageListHeaderCell : NSTableHeaderCell
{
    unsigned long long _imageAlignment;	// 24 = 0x18
    MessageListCell *_realCell;	// 32 = 0x20
}

@property(retain, nonatomic) MessageListCell *realCell; // @synthesize realCell=_realCell;
- (void).cxx_destruct;	// IMP=0x00000001001f28c6
- (void)setImageAlignment:(unsigned long long)arg1;	// IMP=0x0000000100014514
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;	// IMP=0x00000001001f2785
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001f2735

@end

