//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MessageListContentShared : NSObject
{
}

+ (BOOL)shouldDisplayMessage:(id)arg1;	// IMP=0x00000001001f14b1
+ (unsigned long long)sizeForMessage:(id)arg1 originalMessageByMessageID:(id)arg2 messageCopiesByMessageID:(id)arg3;	// IMP=0x00000001001f1274
+ (long long)messageFlagsForMessage:(id)arg1 size:(unsigned long long *)arg2 appliedFlagColors:(id *)arg3 conversationFlags:(unsigned long long *)arg4 originalMessageByMessageID:(id)arg5 messageCopiesByMessageID:(id)arg6;	// IMP=0x00000001001f0d4c
+ (id)messagesIncludingHiddenCopies:(id)arg1 originalMessageByMessageID:(id)arg2 messageCopiesByMessageID:(id)arg3;	// IMP=0x00000001001f0872

@end

