//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MessageViewerSearchField;

@protocol MessageViewerSearchFieldFocusDelegate <NSObject>
- (void)searchFieldDidBeginSearching:(MessageViewerSearchField *)arg1;
- (void)searchFieldDidEndSearching:(MessageViewerSearchField *)arg1;
@end

