//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MFMessageSortingValueDelegate-Protocol.h"

@class NSArray, NSPredicate;
@protocol MessageList, MessageListContentChange;

@protocol MessageListDelegate <MFMessageSortingValueDelegate>
@property(readonly, nonatomic) NSPredicate *filterPredicate;
- (void)messageList:(id <MessageList>)arg1 didUpdateWithContentChange:(id <MessageListContentChange>)arg2;
- (NSArray *)arrayOfSortOrders;
@end

