//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSTableView;

@protocol MessageListContentChange <NSObject>
- (void)incrementChangeIndexesBy:(unsigned long long)arg1;
- (unsigned long long)shiftIndex:(unsigned long long)arg1;
- (void)applyToTableView:(NSTableView *)arg1;
@end

