//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MCMessage, NSArray, NSDictionary;
@protocol MessageListDelegate;

@protocol MessageList <NSObject>
@property(readonly, nonatomic) unsigned long long totalMessageCount;
@property(readonly, copy, nonatomic) NSArray *unrolledObjects;
@property(readonly, nonatomic) __weak id <MessageListDelegate> delegate;
- (unsigned long long)adjustedIndexOfMessage:(MCMessage *)arg1 adjustForChildren:(BOOL)arg2;
- (void)removeMessages:(NSArray *)arg1 andReplaceMessages:(NSDictionary *)arg2 animate:(BOOL)arg3;
- (void)addPrimaryMessages:(NSArray *)arg1 secondaryMessages:(NSArray *)arg2;
- (void)updateMessages:(NSArray *)arg1;
- (void)applyFilter;
- (void)invert;
- (void)resort;
@end

