//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MessageListContentProvider, MessageListContentProviderTaskInfo, NSNumber;

@protocol MessageListContentProviderDelegate <NSObject>
- (void)messageListContentProviderConversationsUpdated:(MessageListContentProvider *)arg1;
- (void)messageListContentProviderDidFinishLoading:(MessageListContentProvider *)arg1;
- (void)messageListContentProvider:(MessageListContentProvider *)arg1 didFinishTaskWithInfo:(MessageListContentProviderTaskInfo *)arg2 taskID:(NSNumber *)arg3;
@end

