//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol MessageDeletionTransfer <NSObject>
@property(readonly, nonatomic) BOOL canBeginTransfer;
- (void)beginTransfer;
@end

