//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSArray, NSStackView, NSTimer;

@interface MessageListSearchProgressView : NSView
{
    NSStackView *_searchingStackView;	// 112 = 0x70
    NSArray *_orderedDotViews;	// 120 = 0x78
    NSTimer *_animationIntervalTimer;	// 128 = 0x80
}

@property(retain, nonatomic) NSTimer *animationIntervalTimer; // @synthesize animationIntervalTimer=_animationIntervalTimer;
@property(retain, nonatomic) NSArray *orderedDotViews; // @synthesize orderedDotViews=_orderedDotViews;
@property(nonatomic) __weak NSStackView *searchingStackView; // @synthesize searchingStackView=_searchingStackView;
- (void).cxx_destruct;	// IMP=0x00000001001f814b
- (void)_stopAnimating;	// IMP=0x00000001001f80d3
- (void)_startAnimating;	// IMP=0x00000001001f80c1
- (void)_stopAnimationIntervalTimer;	// IMP=0x00000001001f8037
- (void)_startAnimationIntervalTimer;	// IMP=0x00000001001f7f98
- (void)_animate:(id)arg1;	// IMP=0x00000001001f7b34
- (void)viewDidMoveToWindow;	// IMP=0x00000001001f7a17
- (void)viewWillMoveToWindow:(id)arg1;	// IMP=0x00000001001f784b

@end

