//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSScrollView.h>

@interface MessageBodyScrollView : NSScrollView
{
}

- (void)tile;	// IMP=0x00000001001d67c3

@end

