//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MessageEditor : NSObject
{
}

+ (id)sharedMessageEditor;	// IMP=0x00000001001d7faa
+ (void)initialize;	// IMP=0x00000001001d7f57
- (void)setBackEnd:(id)arg1;	// IMP=0x00000001001d81f8
- (id)objectSpecifier;	// IMP=0x00000001001d816e
- (void)dealloc;	// IMP=0x00000001001d80be
- (id)init;	// IMP=0x00000001001d7fbb

@end

