//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@interface MessageFilterSelectorCellView : NSTableCellView
{
    BOOL _checked;	// 108 = 0x6c
}

@property(nonatomic) BOOL checked; // @synthesize checked=_checked;

@end

