//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextView.h>

@protocol MessageTextViewDelegate;

@interface MessageTextView : NSTextView
{
}

- (id)accessibilityLabel;	// IMP=0x00000001002010a6
- (BOOL)isAccessibilityElement;	// IMP=0x0000000100201060
- (BOOL)isAccessibilitySelectorAllowed:(SEL)arg1;	// IMP=0x0000000100201021
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x0000000100084c63
- (void)saveAs:(id)arg1;	// IMP=0x0000000100200faf
- (void)showPrintPanel:(id)arg1;	// IMP=0x0000000100200f3d
- (void)toggleShowControlCharacters:(id)arg1;	// IMP=0x0000000100200ecb
- (id)menuForEvent:(id)arg1;	// IMP=0x0000000100200e0a
- (BOOL)validateMenuItem:(id)arg1;	// IMP=0x0000000100200d6f
- (BOOL)acceptsFirstResponder;	// IMP=0x0000000100084bc6
@property __weak id <MessageTextViewDelegate> delegate;

@end

