//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFAccount.h>

@interface MFAccount (MailUIExtras)
- (id)authSchemeBindingProxies;	// IMP=0x0000000100096a3e
@end

