//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Email/EMListUnsubscribeSuggestion.h>

#import "SGSuggestionDelegate-Protocol.h"

@class NSOperationQueue, NSString;

@interface MFListUnsubscribeSuggestion_macOS : EMListUnsubscribeSuggestion <SGSuggestionDelegate>
{
}

- (void)unsubscribe;	// IMP=0x0000000100226e14
- (void)presentViewController:(id)arg1;	// IMP=0x0000000100226e0e
- (void)presentAlert:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100226e08
- (void)dismissViewController:(id)arg1;	// IMP=0x0000000100226e02
- (long long)suggestionsUIContext;	// IMP=0x0000000100226dfa
- (void)suggestionWasUpdated:(id)arg1;	// IMP=0x0000000100226df4
- (void)suggestion:(id)arg1 actionFinished:(BOOL)arg2;	// IMP=0x0000000100226dee
- (id)suggestionPrimaryActionViewController;	// IMP=0x0000000100226c3a
- (id)suggestionCategoryImage;	// IMP=0x0000000100226bc0
- (id)suggestionDismissAction;	// IMP=0x0000000100226b02
- (id)suggestionPrimaryAction;	// IMP=0x00000001002266bd
@property(readonly, nonatomic) NSOperationQueue *deliverQueue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

