//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@interface MFListUnsubscribeSuggestionPopoverViewController : NSViewController
{
    CDUnknownBlockType _unsubscribeBlock;	// 16 = 0x10
    CDUnknownBlockType _ignoreBlock;	// 24 = 0x18
}

@property(copy, nonatomic) CDUnknownBlockType ignoreBlock; // @synthesize ignoreBlock=_ignoreBlock;
@property(copy, nonatomic) CDUnknownBlockType unsubscribeBlock; // @synthesize unsubscribeBlock=_unsubscribeBlock;
- (void).cxx_destruct;	// IMP=0x0000000100227025
- (void)dismiss:(id)arg1;	// IMP=0x0000000100226faa
- (void)unsubscribe:(id)arg1;	// IMP=0x0000000100226f77

@end

