//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MCMessage, MFMessageThread;

@protocol MFMessageSortingValueDelegate
- (long long)sortingUniqueIdentifierForMessageThread:(MFMessageThread *)arg1;
- (long long)sortingMessageFlagsForMessage:(MCMessage *)arg1 appliedFlagColors:(id *)arg2 conversationFlags:(unsigned long long *)arg3;
- (unsigned long long)sortingSizeForMessage:(MCMessage *)arg1;
@end

