//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFSignature.h>

@interface MFSignature (Scripting)
- (id)objectSpecifier;	// IMP=0x0000000100227334
- (void)setSignatureContents:(id)arg1;	// IMP=0x000000010022727d
- (id)signatureContents;	// IMP=0x00000001002270da
- (void)setSignatureName:(id)arg1;	// IMP=0x00000001002270c8
- (id)signatureName;	// IMP=0x0000000100227056
@end

