//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MSDiagnosticManager, MSSearchSessionController;

@protocol MSSearchSessionControllerDataSource <NSObject>
@property(readonly, nonatomic) MSDiagnosticManager *diagnosticManager;
- (int)emailProviderForSearchSessionController:(MSSearchSessionController *)arg1;
- (unsigned long long)percentOfMessagesIndexedForSearchSessionController:(MSSearchSessionController *)arg1;
- (unsigned long long)numberOfMessagesLeftToIndexForSearchSessionController:(MSSearchSessionController *)arg1;
@end

