//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailSupport/MSSearchSessionController.h>

@interface MSSearchSessionController (MailAdditions)
- (void)mail_addNewEngagementWithSuggestions:(id)arg1 searchScope:(BOOL)arg2;	// IMP=0x00000001001c2f74
@end

