//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSFormatter.h>

@interface MTMBytesFormatter : NSFormatter
{
}

- (id)stringForObjectValue:(id)arg1;	// IMP=0x0000000100229161

@end

