//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@interface MTMFlagsCell : NSTextFieldCell
{
}

- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;	// IMP=0x0000000100239ffd
- (id)imageForFlags:(unsigned long long)arg1;	// IMP=0x0000000100239b80

@end

