//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSPredicate.h>

@interface MTMMessageChangedPredicate : NSPredicate
{
}

+ (id)messageChangedPredicate;	// IMP=0x000000010023de29
- (BOOL)evaluateWithObject:(id)arg1;	// IMP=0x000000010023de74

@end

