//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSPredicate.h>

@interface MTMMailboxChangedPredicate : NSPredicate
{
}

+ (id)mailboxChangedPredicate;	// IMP=0x000000010023df4d
- (BOOL)evaluateWithObject:(id)arg1;	// IMP=0x000000010023df98

@end

