//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTMFlagsCell.h"

@interface MTMReadCell : MTMFlagsCell
{
}

- (id)imageForFlags:(unsigned long long)arg1;	// IMP=0x000000010023a13a

@end

