//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MTMScroller;

@protocol MTMScrollerDelegate <NSObject>
- (void)scrollerWasMovedByUser:(MTMScroller *)arg1;
- (void)scrollerWillBeMovedByUser:(MTMScroller *)arg1;
@end

