//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTMMailbox.h"

@class NSString;

@interface MTMSpecialMailbox : MTMMailbox
{
    BOOL _isObserving;	// 8 = 0x8
}

+ (Class)specialMailboxClassForMailboxType:(long long)arg1;	// IMP=0x000000010023a8e9
+ (Class)rootMailboxClass;	// IMP=0x000000010023a8d0
@property(nonatomic) BOOL isObserving; // @synthesize isObserving=_isObserving;
- (id)identifier;	// IMP=0x000000010023aa42
@property(readonly, copy, nonatomic) NSString *recoverDisplayName;

@end

