//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableView.h>

@class NSArrayController;

@interface MTMTableView : NSTableView
{
    NSArrayController *_messagesController;	// 136 = 0x88
}

@property(retain, nonatomic) NSArrayController *messagesController; // @synthesize messagesController=_messagesController;
- (void).cxx_destruct;	// IMP=0x000000010023ddc6

@end

