//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

@interface MTMWindow : NSWindow
{
}

- (double)animationResizeTime:(struct CGRect)arg1;	// IMP=0x000000010023ddd9

@end

