//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MUITokenAddress;

@protocol MUITokenAddressDelegate <NSObject>
- (BOOL)tokenAddressIsBlocked:(MUITokenAddress *)arg1;
- (BOOL)tokenAddressIsVIP:(MUITokenAddress *)arg1;
- (void)tokenAddress:(MUITokenAddress *)arg1 didSelectAction:(long long)arg2;
@end

