//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MVComposeAccessoryViewOwner : NSObject
{
}

+ (id)composeAccessoryViewOwner;	// IMP=0x0000000100245089
- (BOOL)messageWillBeSaved:(id)arg1;	// IMP=0x00000001002450a3

@end

