//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

@interface MVLinkButton : NSButton
{
}

- (void)resetCursorRects;	// IMP=0x00000001000ac93e
- (struct NSEdgeInsets)alignmentRectInsets;	// IMP=0x00000001000ac83d

@end

