//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AccountInformationController.h"

@interface NoEmailChildAccountInformationController : AccountInformationController
{
    BOOL _isEnabling;	// 16 = 0x10
}

@property(nonatomic) BOOL isEnabling; // @synthesize isEnabling=_isEnabling;
- (void)setUpUIForAccount:(id)arg1;	// IMP=0x00000001002456b8
- (void)setAccountIsEnabled:(BOOL)arg1;	// IMP=0x0000000100245507

@end

