//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@interface NoSelectionPlaceholderViewController : NSViewController
{
}

- (void)loadView;	// IMP=0x000000010024573d

@end

