//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSVisualEffectView.h>

@interface NoSelectionPlaceholderView : NSVisualEffectView
{
}

- (void)_noSelectionPlaceholderViewViewCommonInit;	// IMP=0x0000000100245726
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010001af82
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001002456df

@end

