//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDatePickerCell;

@protocol NSDatePickerCellDelegate <NSObject>

@optional
- (void)datePickerCell:(NSDatePickerCell *)arg1 validateProposedDateValue:(id *)arg2 timeInterval:(double *)arg3;
@end

