//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSWindow;

@protocol NSInspectorBarClient <NSObject>
@property(readonly) NSWindow *window;
@property(readonly) NSArray *inspectorBarItemIdentifiers;
@end

