//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSOutlineView.h>

@interface NSOutlineView (MailAdditions)
- (id)copyOfItemAndDescendance:(id)arg1;	// IMP=0x0000000100245e1c
- (void)_collectDescendants:(id *)arg1 ofItem:(id)arg2;	// IMP=0x0000000100245c55
- (BOOL)item:(id)arg1 isDescendantOf:(id)arg2;	// IMP=0x0000000100245b9f
@end

