//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButton.h>

@interface NSPopUpButton (MailAdditions)
- (void)reloadData;	// IMP=0x000000010007f7c7
@end

