//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSpellChecker.h>

@interface NSSpellChecker (AllocationOverride)
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100045459
@end

