//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (HTMLConversion)
- (id)webArchiveForRange:(struct _NSRange)arg1 signatureID:(id *)arg2;	// IMP=0x0000000100296482
- (id)webArchiveForRange:(struct _NSRange)arg1;	// IMP=0x0000000100296301
@property(readonly, copy, nonatomic) NSString *markupString;
@end

