//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSView;

@protocol NSTextFinderAsynchronousDocumentFindMatch <NSObject>
@property(readonly, retain, nonatomic) NSArray *textRects;
@property(readonly, retain, nonatomic) NSView *containingView;
- (void)generateTextImage:(void (^)(NSImage *))arg1;
@end

