//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

@interface NSWindow (BetterDescription)
- (id)debugDescription;	// IMP=0x000000010022761b
@end

