//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GenericAttachmentFetcher.h"

@interface PhotoExporter : GenericAttachmentFetcher
{
}

+ (void)exportPhotoAttachments:(id)arg1;	// IMP=0x000000010024a87a
+ (BOOL)isPhotoAttachment:(id)arg1;	// IMP=0x000000010024a59b
- (void)downloadedAllAttachments;	// IMP=0x000000010024b02f
- (void)_exportAttachments:(id)arg1;	// IMP=0x000000010024aa8e

@end

