//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class MailBundle, NSButton, NSTextField, PlugInsViewController;

@interface PlugInTableCellView : NSTableCellView
{
    NSButton *_checkbox;	// 112 = 0x70
    NSTextField *_label;	// 120 = 0x78
    PlugInsViewController *_viewController;	// 128 = 0x80
    MailBundle *_bundle;	// 136 = 0x88
}

@property(nonatomic) __weak MailBundle *bundle; // @synthesize bundle=_bundle;
@property(nonatomic) __weak PlugInsViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) __weak NSTextField *label; // @synthesize label=_label;
@property(nonatomic) __weak NSButton *checkbox; // @synthesize checkbox=_checkbox;
- (void).cxx_destruct;	// IMP=0x000000010024b2a3
- (void)_takeStateFromCheckbox:(id)arg1;	// IMP=0x000000010024b156

@end

