//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

@interface PreferencesWindow : NSWindow
{
}

- (BOOL)validateUserInterfaceItem:(id)arg1;	// IMP=0x0000000100255794

@end

