//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PrintingManager.h"

@class NSMutableArray, NSPDFInfo;

@interface PrintingManagerForExportAsPDF : PrintingManager
{
    NSMutableArray *_exportJobs;	// 8 = 0x8
    NSPDFInfo *_pdfInfo;	// 16 = 0x10
}

@property(retain, nonatomic) NSPDFInfo *pdfInfo; // @synthesize pdfInfo=_pdfInfo;
@property(retain, nonatomic) NSMutableArray *exportJobs; // @synthesize exportJobs=_exportJobs;
- (void).cxx_destruct;	// IMP=0x000000010025b048
- (void)_generateJobTitleAndPrintInfoForExportJob:(id)arg1;	// IMP=0x000000010025ac0d
- (void)_getSaveURLFromUser:(CDUnknownBlockType)arg1;	// IMP=0x000000010025a8f4
- (void)_runEnumeratedExportJobs:(id)arg1;	// IMP=0x000000010025a466
- (void)_generatePrintingHTMLForEnumeratedExportJobs:(id)arg1;	// IMP=0x000000010025a242
- (void)dispatch;	// IMP=0x00000001002595de
- (id)progressMessage;	// IMP=0x0000000100259578
- (void)dealloc;	// IMP=0x0000000100259526

@end

