//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageCell.h>

@class NSProgressIndicator;

@interface ProgressIndicatorCell : NSImageCell
{
    NSProgressIndicator *_progressIndicator;	// 24 = 0x18
}

@property(nonatomic) __weak NSProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
- (void).cxx_destruct;	// IMP=0x000000010025c491
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;	// IMP=0x000000010025c2d9

@end

