//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface ReplyButtonCell : NSButtonCell
{
}

- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;	// IMP=0x0000000100260690

@end

