//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ReportBugWindowController;

@protocol ReportBugWindowControllerDelegate <NSObject>
- (void)controller:(ReportBugWindowController *)arg1 runSysdiagnoseWithObfuscation:(BOOL)arg2;
- (void)controller:(ReportBugWindowController *)arg1 saveOnlyEditingWithObfuscation:(BOOL)arg2;
- (void)closeWindowForController:(ReportBugWindowController *)arg1;
@end

