//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSConcreteTextStorage.h>

@interface ScriptableMessageTextStorage : NSConcreteTextStorage
{
}

- (void)setAttributes:(id)arg1 range:(struct _NSRange)arg2;	// IMP=0x00000001000e3a14
- (void)addAttribute:(id)arg1 value:(id)arg2 range:(struct _NSRange)arg3;	// IMP=0x00000001000e3970
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withAttributedString:(id)arg2;	// IMP=0x00000001000e38ff

@end

