//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "LazyMenuSegmentedCell.h"

@interface SegmentedToolbarItemSegmentedCell : LazyMenuSegmentedCell
{
}

- (double)_menuDelayTimeForSegment:(long long)arg1;	// IMP=0x0000000100046bce

@end

