//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@interface SelfSizingTextField : NSTextField
{
}

- (struct CGSize)intrinsicContentSize;	// IMP=0x00000001002707a6

@end

