//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSProgressIndicator.h>

@interface SelfAnimatingProgressIndicator : NSProgressIndicator
{
}

- (void)setIndeterminate:(BOOL)arg1;	// IMP=0x0000000100019314

@end

