//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSSharingServicePicker, ServicesRolloverView;

@protocol ServicesRolloverViewDelegate <NSObject>
- (NSSharingServicePicker *)pickerForRolloverCalloutView:(ServicesRolloverView *)arg1;
@end

