//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface SignImageValueTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;	// IMP=0x0000000100167605
+ (void)initialize;	// IMP=0x0000000100167581
- (id)transformedValue:(id)arg1;	// IMP=0x000000010016761e

@end

