//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface SMIMEEncryptionState : NSObject
{
    BOOL _gatheringCertificates;	// 8 = 0x8
    NSDictionary *_encryptionCertificates;	// 16 = 0x10
}

@property(readonly, nonatomic) NSDictionary *encryptionCertificates; // @synthesize encryptionCertificates=_encryptionCertificates;
@property(readonly, nonatomic, getter=isGatheringCertificates) BOOL gatheringCertificates; // @synthesize gatheringCertificates=_gatheringCertificates;
- (void).cxx_destruct;	// IMP=0x00000001000df2f9
- (id)initWithGatheringCertificates:(BOOL)arg1 encryptionCertificates:(id)arg2;	// IMP=0x00000001000df267

@end

