//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface SnippetColorTransformer : NSValueTransformer
{
}

+ (BOOL)allowsReverseTransformation;	// IMP=0x0000000100260a73
+ (Class)transformedValueClass;	// IMP=0x0000000100260a5a
- (id)transformedValue:(id)arg1;	// IMP=0x0000000100260a7b

@end

