//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CALayer, NSView, StackController;

@protocol StackDataSource <NSObject>
@property(readonly, nonatomic) NSView *stackContainerView;
- (void)stackController:(StackController *)arg1 loadDataForItem:(id)arg2 inLayer:(CALayer *)arg3;
- (BOOL)stackController:(StackController *)arg1 isDataLoadedForItem:(id)arg2 inLayer:(CALayer *)arg3;
- (CALayer *)stackController:(StackController *)arg1 layerForItem:(id)arg2;
- (CALayer *)stackContainerLayerForStackController:(StackController *)arg1;
@end

