//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSFormatter.h>

@interface SubjectFormatter : NSFormatter
{
}

- (BOOL)isPartialStringValid:(id)arg1 newEditingString:(id *)arg2 errorDescription:(id *)arg3;	// IMP=0x00000001002964a6
- (BOOL)getObjectValue:(id *)arg1 forString:(id)arg2 errorDescription:(id *)arg3;	// IMP=0x0000000100052283
- (id)editingStringForObjectValue:(id)arg1;	// IMP=0x0000000100296494
- (id)attributedStringForObjectValue:(id)arg1 withDefaultAttributes:(id)arg2;	// IMP=0x0000000100051730
- (id)stringForObjectValue:(id)arg1;	// IMP=0x000000010005041b

@end

