//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GenericAttachmentFetcher.h"

@class NSString;

@interface TemporaryAttachmentOpener : GenericAttachmentFetcher
{
    NSString *_applicationPath;	// 8 = 0x8
}

@property(readonly, copy, nonatomic) NSString *applicationPath; // @synthesize applicationPath=_applicationPath;
- (void).cxx_destruct;	// IMP=0x00000001002a3d08
- (double)temporaryFolderTimeout;	// IMP=0x00000001002a3ce7
- (void)didSaveAttachment:(id)arg1 toPath:(id)arg2;	// IMP=0x00000001002a3b47
- (void)_openAttachmentAtPath:(id)arg1;	// IMP=0x00000001002a3aa7
- (void)downloadedAllAttachments;	// IMP=0x00000001002a3968
- (id)initWithAttachmentViewControllers:(id)arg1;	// IMP=0x00000001002a3899
- (id)initWithAttachmentViewControllers:(id)arg1 applicationPath:(id)arg2;	// IMP=0x00000001002a37e8

@end

