//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MailApp;

@protocol TerminationHandler <NSObject>
- (void)nowWouldBeAGoodTimeToTerminate:(MailApp *)arg1;

@optional
- (BOOL)needsToPromptUserBeforeTermination:(MailApp *)arg1;
@end

