//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MessageList-Protocol.h"

@class NSArray;
@protocol ThreadedMessageListDelegate;

@protocol ThreadSupportingMessageList <MessageList>
@property(readonly, nonatomic) __weak id <ThreadedMessageListDelegate> delegate;
- (void)closeAllThreads;
- (void)closeThreads:(NSArray *)arg1;
- (void)openAllThreads;
- (void)openThreads:(NSArray *)arg1;
@end

