//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TLSClientPopUpConfiguration : NSObject
{
}

+ (void)configureTLSCertificatesPopUp:(id)arg1 withTLSIdentities:(id)arg2;	// IMP=0x0000000100096ce7

@end

