//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@interface ToCCIndicator : NSTextField
{
}

+ (Class)cellClass;	// IMP=0x00000001002abb5b
- (void)_toCCIndicatorCommonInit;	// IMP=0x00000001002abc1a
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001002abbd3
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001002abb74

@end

