//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@interface ToCCIndicatorCell : NSTextFieldCell
{
}

- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;	// IMP=0x00000001002aba3e
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;	// IMP=0x00000001002ab9c5
- (id)textColor;	// IMP=0x00000001002ab947
- (id)backgroundColor;	// IMP=0x00000001002ab889
- (BOOL)_isInSelectedRow;	// IMP=0x00000001002ab828
- (id)_parentRow;	// IMP=0x00000001002ab789

@end

