//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableView.h>

@interface ToggleSelectTableView : NSTableView
{
}

- (void)mouseDown:(id)arg1;	// IMP=0x00000001002abc5e

@end

