//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@interface VerifyingServerSettingsController : NSViewController
{
    BOOL _isVerifying;	// 16 = 0x10
}

@property(nonatomic) BOOL isVerifying; // @synthesize isVerifying=_isVerifying;

@end

