//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSURLDownloadDelegate-Protocol.h"

@class NSWindow, WebDownload;

@protocol WebDownloadDelegate <NSURLDownloadDelegate>

@optional
- (NSWindow *)downloadWindowForAuthenticationSheet:(WebDownload *)arg1;
@end

