//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/WebFrame.h>

@interface WebFrame (SizingExtras)
- (void)selectAttachmentView:(id)arg1;	// IMP=0x00000001002b8ff1
- (void)adjustAttachmentView:(id)arg1;	// IMP=0x00000001002b8e82
- (void)adjustToDocumentView;	// IMP=0x00000001002b8990
- (void)_setSize:(struct CGSize)arg1 ofElement:(id)arg2;	// IMP=0x00000001002b8853
@end

