//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/WebHTMLView.h>

@interface WebHTMLView (MailAdditions)
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010004e70a
- (void)changeDocumentBackgroundColor:(id)arg1;	// IMP=0x000000010014e0cd
@end

