//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WebViewLoadOperation.h"

@class WKWebView;

@interface WebViewLoadOperationWK2 : WebViewLoadOperation
{
    WKWebView *_webView;	// 16 = 0x10
    CDUnknownBlockType _loader;	// 24 = 0x18
    BOOL _didStopObservingWebView;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001002c3ea2
- (void)_stopLoading;	// IMP=0x00000001002c3e85
- (void)_startLoading;	// IMP=0x00000001002c3e61
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001002c3d55
- (void)_stopObservingWebView;	// IMP=0x00000001002c3d0a
- (id)initWithWebView:(id)arg1 loader:(CDUnknownBlockType)arg2;	// IMP=0x00000001002c3b76

@end

