//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WebViewLoadOperation.h"

@class WebView;

@interface WebViewLoadOperationWK1 : WebViewLoadOperation
{
    WebView *_webView;	// 8 = 0x8
    CDUnknownBlockType _loader;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001002c417d
- (void)_webViewDidLoad:(id)arg1;	// IMP=0x00000001002c416b
- (void)_stopLoading;	// IMP=0x00000001002c4123
- (void)_startLoading;	// IMP=0x00000001002c40ff
- (void)_stopObservingWebView;	// IMP=0x00000001002c4097
- (id)initWithWebView:(id)arg1 loader:(CDUnknownBlockType)arg2;	// IMP=0x00000001002c3ed3

@end

