//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/WebView.h>

@interface WebView (MailExtras)
- (void)setAllDelegates:(id)arg1;	// IMP=0x000000010005dc36
@end

