//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _MFAllSignaturesAccount : NSObject
{
}

- (id)displayName;	// IMP=0x0000000000205814
- (id)identifier;	// IMP=0x00000000002057f5

@end

