//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _MFCloudDocumentRegister : NSObject
{
}

+ (void)_registerContainer:(id)arg1 syncHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000000230a4c

@end

