//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MFEWSAccount;

@interface _MFEWSAutodiscoveryTimerTarget : NSObject
{
    MFEWSAccount *_account;	// 8 = 0x8
}

@property(nonatomic) __weak MFEWSAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;	// IMP=0x0000000000060d36
- (void)kickOffReautodiscovery:(id)arg1;	// IMP=0x0000000000060c44

@end

