//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@interface _MFMessageSortingValueNumberOfAttachments : MFMessageSortingValue
{
    unsigned long long _numberOfAttachments;	// 8 = 0x8
}

@property(nonatomic) unsigned long long numberOfAttachments; // @synthesize numberOfAttachments=_numberOfAttachments;
- (id)description;	// IMP=0x000000000019e71c

@end

