//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@interface _MFMessageSortingValueColor : MFMessageSortingValue
{
    int _colorForSort;	// 8 = 0x8
}

@property(nonatomic) int colorForSort; // @synthesize colorForSort=_colorForSort;
- (id)description;	// IMP=0x000000000019e492

@end

