//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@interface _MFMessageSortingValueMessageFlags : MFMessageSortingValue
{
    unsigned char _flagColorSet;	// 8 = 0x8
    long long _messageFlags;	// 16 = 0x10
}

@property(nonatomic) unsigned char flagColorSet; // @synthesize flagColorSet=_flagColorSet;
@property(nonatomic) long long messageFlags; // @synthesize messageFlags=_messageFlags;
- (id)description;	// IMP=0x000000000019e5c1

@end

