//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSEnumerator.h>

@interface _MFMailboxChildrenEnumerator : NSEnumerator
{
    struct __CFTree *_root;	// 8 = 0x8
    struct __CFTree *_currentTree;	// 16 = 0x10
    BOOL _includeHidden;	// 24 = 0x18
}

@property(readonly, nonatomic) BOOL includeHidden; // @synthesize includeHidden=_includeHidden;
- (id)nextObject;	// IMP=0x000000000016c7a7
- (void)dealloc;	// IMP=0x000000000016c766
- (id)init;	// IMP=0x000000000016c697
- (id)initWithTree:(struct __CFTree *)arg1 includeHiddenChildren:(BOOL)arg2;	// IMP=0x000000000016c5de

@end

