//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EmailDaemon/EDPersistedMessageQueryIterator.h>

#import <Mail/MFMessageConsumer-Protocol.h>
#import <Mail/MFQueryProgressMonitor-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _MFMessagePersistenceQueryIterator : EDPersistedMessageQueryIterator <MFMessageConsumer, MFQueryProgressMonitor>
{
}

- (void)finishedSendingMessages;	// IMP=0x00000000001879e0
- (void)newMessagesAvailable:(id)arg1 secondaryMessages:(id)arg2 fromUpdate:(BOOL)arg3;	// IMP=0x00000000001879aa

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) BOOL shouldCancel;
@property(readonly) Class superclass;

@end

