//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@interface _MFMessageSortingValueMessageSize : MFMessageSortingValue
{
    unsigned long long _messageSize;	// 8 = 0x8
}

@property(nonatomic) unsigned long long messageSize; // @synthesize messageSize=_messageSize;
- (id)description;	// IMP=0x000000000019e683

@end

