//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@class ECSubject;

@interface _MFMessageSortingValueSubject : MFMessageSortingValue
{
    ECSubject *_subject;	// 8 = 0x8
}

@property(copy, nonatomic) ECSubject *subject; // @synthesize subject=_subject;
- (id)description;	// IMP=0x000000000019e7f7
- (void)dealloc;	// IMP=0x000000000019e7b5

@end

