//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@interface _MFMessageSortingValueDateSent : MFMessageSortingValue
{
    double _dateSentAsTimeIntervalSince1970;	// 8 = 0x8
}

@property(nonatomic) double dateSentAsTimeIntervalSince1970; // @synthesize dateSentAsTimeIntervalSince1970=_dateSentAsTimeIntervalSince1970;
- (id)description;	// IMP=0x000000000019ea07

@end

