//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSEnumerator.h>

@interface _MFMailboxEnumerator : NSEnumerator
{
    struct __CFTree *_startTree;	// 8 = 0x8
    struct __CFTree *_lastTree;	// 16 = 0x10
}

- (id)nextObject;	// IMP=0x000000000016bd4d
- (void)dealloc;	// IMP=0x000000000016bd0c
- (id)init;	// IMP=0x000000000016bc3d
- (id)initWithTree:(struct __CFTree *)arg1;	// IMP=0x000000000016bb74

@end

