//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@interface _MFMessageSortingValueDateReceived : MFMessageSortingValue
{
    double _dateReceivedAsTimeIntervalSince1970;	// 8 = 0x8
}

@property(nonatomic) double dateReceivedAsTimeIntervalSince1970; // @synthesize dateReceivedAsTimeIntervalSince1970=_dateReceivedAsTimeIntervalSince1970;
- (id)description;	// IMP=0x000000000019e96f

@end

