//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@class NSString;

@interface _MFMessageSortingValueSender : MFMessageSortingValue
{
    NSString *_senderDisplayName;	// 8 = 0x8
}

@property(copy, nonatomic) NSString *senderDisplayName; // @synthesize senderDisplayName=_senderDisplayName;
- (id)description;	// IMP=0x000000000019e3f7
- (void)dealloc;	// IMP=0x000000000019e3b5

@end

