//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@class NSArray;

@interface _MFMessageSortingValueTo : MFMessageSortingValue
{
    NSArray *_to;	// 8 = 0x8
}

@property(copy, nonatomic) NSArray *to; // @synthesize to=_to;
- (id)description;	// IMP=0x000000000019e8d4
- (void)dealloc;	// IMP=0x000000000019e892

@end

