//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@interface _MFMessageSortingValueDateLastViewed : MFMessageSortingValue
{
    double _dateLastViewedAsTimeIntervalSince1970;	// 8 = 0x8
}

@property(nonatomic) double dateLastViewedAsTimeIntervalSince1970; // @synthesize dateLastViewedAsTimeIntervalSince1970=_dateLastViewedAsTimeIntervalSince1970;
- (id)description;	// IMP=0x000000000019e529

@end

