//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@interface _MFMessageSortingValueLibraryID : MFMessageSortingValue
{
    long long _libraryID;	// 8 = 0x8
}

@property(nonatomic) long long libraryID; // @synthesize libraryID=_libraryID;
- (id)description;	// IMP=0x000000000019eb7a

@end

