//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Mail/MFQueryProgressMonitor-Protocol.h>

@class MCActivityMonitor, NSString;
@protocol MFQueryProgressMonitor;

@interface _MFProgressHandlerMonitorContext : NSObject <MFQueryProgressMonitor>
{
    id <MFQueryProgressMonitor> _progressMonitor;	// 8 = 0x8
    MCActivityMonitor *_activityMonitor;	// 16 = 0x10
}

@property(nonatomic) __weak MCActivityMonitor *activityMonitor; // @synthesize activityMonitor=_activityMonitor;
@property(nonatomic) __weak id <MFQueryProgressMonitor> progressMonitor; // @synthesize progressMonitor=_progressMonitor;
- (void).cxx_destruct;	// IMP=0x0000000000109d12
@property(readonly, nonatomic) BOOL shouldCancel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

