//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMailbox.h>

@interface _MFRootlessMailbox : MFMailbox
{
}

- (id)storeForMailbox:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x000000000013f5c3
- (id)fullPath;	// IMP=0x000000000013f5b1
- (id)displayName;	// IMP=0x000000000013f52a

@end

