//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/ECMailbox-Protocol.h>

@class NSString;

@protocol EDIndexableMailbox <ECMailbox>
@property(readonly, copy, nonatomic) NSString *URLString;
@end

