//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/ECMessage-Protocol.h>

@protocol EDLibraryMessage <ECMessage>
@property(readonly, nonatomic) long long libraryID;
@end

