//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ExchangeWebServices/EWSPathToExtendedFieldType.h>

@interface EWSPathToExtendedFieldType (MessageAdditions)
+ (id)newExtendedFieldTypeForPropertyId:(long long)arg1;	// IMP=0x000000000009a3bd
+ (id)newExtendedFieldTypeForPropertyTag:(id)arg1;	// IMP=0x000000000009a159
+ (id)_newExtendedFieldTypeForPropertyTag:(id)arg1 propertyType:(long long)arg2;	// IMP=0x000000000009a0e4
@end

