//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPMailbox.h>

@class MFMailbox;

@interface IMAPMailbox (MCMailboxAdapter)
@property(readonly, nonatomic) MFMailbox *mailMailbox;
@end

