//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MailFramework : NSObject
{
}

+ (void)setUserAgent:(id)arg1;	// IMP=0x00000000000ae5e2
+ (id)userAgent;	// IMP=0x00000000000ae587
+ (id)bundle;	// IMP=0x00000000000ae325

@end

