//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Mail/EDAccountsProvider-Protocol.h>

@class NSArray;

@interface MFAccountProvider : NSObject <EDAccountsProvider>
{
}

@property(readonly, copy, nonatomic) NSArray *receivingAddresses;
- (id)mailAccounts;	// IMP=0x0000000000013443

@end

