//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Mail/EDAccountFactory-Protocol.h>

@interface MFAccountFactory_macOS : NSObject <EDAccountFactory>
{
}

- (id)accountWithSystemAccount:(id)arg1;	// IMP=0x000000000000b43e
- (id)accountWithIdentifier:(id)arg1;	// IMP=0x000000000000b425

@end

