//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class NSString;

@protocol MFActivityProgressUpdater <NSObject>
- (void)resetProgressItemsWithTotal:(unsigned long long)arg1 andStatusMessage:(NSString *)arg2;
- (void)incrementProgressIndicator;
- (void)setProgressItemTotal:(unsigned long long)arg1;
@end

