//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFAccountURLMigrator : NSObject
{
}

+ (id)accountURLStringFromV1V2PersistenceAccountAttributes:(id)arg1 syncable:(BOOL)arg2;	// IMP=0x000000000001dc9a
+ (id)connectionHostnameAccountURLStringFromSystemAccount:(id)arg1;	// IMP=0x000000000001dab3
+ (id)accountURLStringWithIdentifierFromSystemAccount:(id)arg1 syncable:(BOOL)arg2;	// IMP=0x000000000001da56

@end

