//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFAddLastSpotlightCheckDateTableUpgradeStep : MFLibraryUpgradeStep
{
}

+ (unsigned long long)targetVersion;	// IMP=0x000000000001e450
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x000000000001e45b

@end

