//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFAddServerMessagesUniquenessIndexUpgradeStep : MFLibraryUpgradeStep
{
}

+ (unsigned long long)targetVersion;	// IMP=0x0000000000022c9d
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x0000000000022ca8

@end

