//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@protocol MFAddProgressMonitor <NSObject>
- (void)setFractionDone:(double)arg1;
@end

