//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFBasicPersistenceMigrator : NSObject
{
}

- (void)migrateToVersion:(long long)arg1;	// IMP=0x0000000000029527

@end

