//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageRule.h>

@interface MFCalendarInviteRule : MFMessageRule
{
}

+ (id)log;	// IMP=0x000000000002da80
- (void)_performAddInvitationAttachmentToCalendarActionOnMessages:(id)arg1;	// IMP=0x000000000002de11
- (void)setIsActive:(BOOL)arg1;	// IMP=0x000000000002ddb7
- (BOOL)isActive;	// IMP=0x000000000002dd64
- (void)performCustomRuleActionOnMessages:(id)arg1;	// IMP=0x000000000002dd52
- (id)description;	// IMP=0x000000000002dce6
- (id)init;	// IMP=0x000000000002db49

@end

