//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFCreateServerLabelsTableUpgradeStep : MFLibraryUpgradeStep
{
}

+ (unsigned long long)targetVersion;	// IMP=0x000000000003f2c2
- (void)_populateFromLocalMessagesTable;	// IMP=0x000000000003f430
- (void)_populateFromIMAPLabelsTable;	// IMP=0x000000000003f3c2
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x000000000003f2cd

@end

