//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFCriteriaUpgrader : NSObject
{
}

+ (id)upgradeCriteriaFromUbiquitousVersion3To4:(id)arg1;	// IMP=0x000000000003fbc5

@end

