//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFCreateConversationsTableUpgradeStep : MFLibraryUpgradeStep
{
}

+ (BOOL)needToPerformFromMinorVersion:(unsigned long long)arg1 initialLastWriteMinorVersion:(unsigned long long)arg2;	// IMP=0x000000000003d36f
+ (unsigned long long)targetVersion;	// IMP=0x000000000003d364
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x000000000003d3b4

@end

