//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@class NSArray;

@interface MFCreateIMAPMessagesUpgradeStep : MFLibraryUpgradeStep
{
    NSArray *_accounts;	// 8 = 0x8
}

+ (unsigned long long)targetVersion;	// IMP=0x000000000003d677
@property(readonly, copy, nonatomic) NSArray *accounts; // @synthesize accounts=_accounts;
- (void).cxx_destruct;	// IMP=0x000000000003e0c4
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x000000000003d7ef
- (id)initWithDatabaseConnection:(id)arg1;	// IMP=0x000000000003d720
- (id)initWithDatabaseConnection:(id)arg1 accounts:(id)arg2;	// IMP=0x000000000003d682

@end

