//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFCreateSearchableAttachmentsTablesUpgradeStep : MFLibraryUpgradeStep
{
}

+ (unsigned long long)targetVersion;	// IMP=0x000000000003f1ae
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x000000000003f1b9

@end

