//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSResponseOperation.h>

@class EWSSetUserOofSettingsResponseType;

@interface MFEWSSetUserOofSettingsResponseOperation : MFEWSResponseOperation
{
}

- (void)executeOperation;	// IMP=0x00000000000a1086
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;	// IMP=0x00000000000a0e60
@property(retain) EWSSetUserOofSettingsResponseType *response;

@end

