//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSMessageActionSyncOperation.h>

@class ECTransferMessageAction;

@interface MFEWSTransferActionSyncOperation : MFEWSMessageActionSyncOperation
{
}

- (void)main;	// IMP=0x00000000000a65ab
- (id)initWithMessageAction:(id)arg1;	// IMP=0x00000000000a6474

// Remaining properties
@property(readonly, nonatomic) ECTransferMessageAction *messageAction; // @dynamic messageAction;

@end

