//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFEWSEventFetcher : NSObject
{
}

+ (id)fetchEventsWithConnection:(id)arg1 forMeetingCancellationItemIdStrings:(id)arg2 error:(id *)arg3;	// IMP=0x0000000000078fc0
+ (id)fetchEventsWithConnection:(id)arg1 forMeetingRequestItemIdStrings:(id)arg2 error:(id *)arg3;	// IMP=0x0000000000078785

@end

