//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageDeliverer.h>

#import <Mail/MFEWSErrorHandler-Protocol.h>

@class MFEWSDeliveryAccount, NSError, NSString;

@interface MFEWSDeliverer : MFMessageDeliverer <MFEWSErrorHandler>
{
    NSError *_error;	// 8 = 0x8
}

@property(retain) NSError *error; // @synthesize error=_error;
- (void).cxx_destruct;	// IMP=0x0000000000076e4c
- (void)handleEWSError:(id)arg1;	// IMP=0x000000000007666e
- (long long)deliverSynchronously;	// IMP=0x0000000000075cf7
- (id)headersForDelivery;	// IMP=0x0000000000075b0a
@property(retain, nonatomic) MFEWSDeliveryAccount *account;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

