//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSNetworkTaskOperation.h>

@class MFEWSMailboxItemsBatch;
@protocol MFEWSFetchMessageMetadataOperationDelegate;

@interface MFEWSFetchMessageMetadataOperation : MFEWSNetworkTaskOperation
{
    id <MFEWSFetchMessageMetadataOperationDelegate> _delegate;	// 8 = 0x8
    MFEWSMailboxItemsBatch *_batch;	// 16 = 0x10
}

+ (id)_propertiesForItemClass:(Class)arg1;	// IMP=0x000000000007ab5f
+ (id)_shapeForType:(Class)arg1;	// IMP=0x000000000007aad4
@property(readonly, nonatomic) MFEWSMailboxItemsBatch *batch; // @synthesize batch=_batch;
@property(nonatomic) __weak id <MFEWSFetchMessageMetadataOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000000007b6f7
- (void)main;	// IMP=0x0000000000079dce
- (id)init;	// IMP=0x0000000000079cf0
- (id)initWithBatch:(id)arg1;	// IMP=0x0000000000079c82

@end

