//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSRequestOperation.h>

@class MFEWSGetItemsResponseOperation, NSArray;

@interface MFEWSGetItemsRequestOperation : MFEWSRequestOperation
{
    NSArray *_EWSItemIds;	// 8 = 0x8
    NSArray *_additionalProperties;	// 16 = 0x10
}

@property(readonly, copy, nonatomic) NSArray *additionalProperties; // @synthesize additionalProperties=_additionalProperties;
@property(readonly, copy, nonatomic) NSArray *EWSItemIds; // @synthesize EWSItemIds=_EWSItemIds;
- (void).cxx_destruct;	// IMP=0x0000000000088734
- (id)prepareRequest;	// IMP=0x0000000000088420
- (id)newResponseOperationWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x00000000000883b4
@property(retain, nonatomic) MFEWSGetItemsResponseOperation *responseOperation;
- (id)activityString;	// IMP=0x00000000000881db
- (id)description;	// IMP=0x000000000008811b
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x000000000008804c
- (id)initWithEWSItemIds:(id)arg1 additionalProperties:(id)arg2 gateway:(id)arg3 errorHandler:(id)arg4;	// IMP=0x0000000000087f60

@end

