//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSTask.h>

#import <Mail/MFEWSRetrievePersistedFolderDataDelegate-Protocol.h>

@class MFEWSRetrievePersistedFolderDataOperation, NSMutableSet, NSString;
@protocol MFEWSMailboxDataCache;

@interface MFEWSRetrievePersistedFolderDataTask : MFEWSTask <MFEWSRetrievePersistedFolderDataDelegate>
{
    MFEWSRetrievePersistedFolderDataOperation *_retrievePersistedFolderDataOperation;	// 8 = 0x8
    NSMutableSet *_urlsNeedingData;	// 16 = 0x10
    id <MFEWSMailboxDataCache> _cache;	// 24 = 0x18
}

@property(readonly, nonatomic) id <MFEWSMailboxDataCache> cache; // @synthesize cache=_cache;
- (void).cxx_destruct;	// IMP=0x00000000000a0519
- (void)recalculatePriorities;	// IMP=0x00000000000a0473
- (id)nextPersistenceOperation;	// IMP=0x00000000000a0387
- (id)nextNetworkOperation;	// IMP=0x00000000000a037f
- (void)retrievePersistedFolderDataOperation:(id)arg1 didRetrieveFolderIDsByURL:(id)arg2 syncStatesByURL:(id)arg3 missedMailboxURLs:(id)arg4;	// IMP=0x000000000009fe73
- (void)operationFinished:(id)arg1;	// IMP=0x000000000009fd1f
@property(retain, nonatomic) MFEWSRetrievePersistedFolderDataOperation *retrievePersistedFolderDataOperation;
- (void)retrieveDataForMailboxURLs:(id)arg1;	// IMP=0x000000000009fc59
- (id)init;	// IMP=0x000000000009fb8a
- (id)initWithMailboxDataCache:(id)arg1 accountName:(id)arg2;	// IMP=0x000000000009fa88

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

