//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class MFEWSGetNewMessageActionsOperation, NSArray;

@protocol MFEWSGetNewMessageActionsOperationDelegate <NSObject>
- (void)getNewMessageActionsOperation:(MFEWSGetNewMessageActionsOperation *)arg1 didGetActions:(NSArray *)arg2;
@end

