//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class ECLocalMessageActionResults, MFEWSMessageActionSyncOperation;

@protocol MFEWSMessageActionSyncOperationDelegate <NSObject>
- (void)messageActionSyncOperationCompleted:(MFEWSMessageActionSyncOperation *)arg1 results:(ECLocalMessageActionResults *)arg2;
@end

