//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSCreateItemResponseOperation.h>

@interface MFEWSCreateEventReplyResponseOperation : MFEWSCreateItemResponseOperation
{
}

- (void)executeOperation;	// IMP=0x000000000006fa67
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;	// IMP=0x000000000006f91a

@end

