//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSMessageActionSyncOperation.h>

@class ECFlagChangeMessageAction;

@interface MFEWSFlagChangeSyncOperation : MFEWSMessageActionSyncOperation
{
}

- (BOOL)_batchedSetFlagsForItems:(id)arg1 inFolder:(id)arg2 messageType:(BOOL)arg3 flagChange:(id)arg4 error:(id *)arg5;	// IMP=0x000000000007d578
- (void)main;	// IMP=0x000000000007c9cb
- (id)initWithMessageAction:(id)arg1;	// IMP=0x000000000007c894

// Remaining properties
@property(readonly, nonatomic) ECFlagChangeMessageAction *messageAction; // @dynamic messageAction;

@end

