//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCTaskHandler.h>

@class MFEWSConnection;

@interface MFEWSNetworkTaskHandler : MCTaskHandler
{
    MFEWSConnection *_connection;	// 8 = 0x8
}

@property(readonly, nonatomic) MFEWSConnection *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;	// IMP=0x000000000009760f
- (id)init;	// IMP=0x000000000009752f
- (id)initWithEWSConnection:(id)arg1;	// IMP=0x00000000000974c1

@end

