//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSRequestOperation.h>

@class MFEWSGetFolderResponseOperation, NSString;

@interface MFEWSRenameFolderRequestOperation : MFEWSRequestOperation
{
    NSString *_folderIdString;	// 8 = 0x8
    NSString *_folderName;	// 16 = 0x10
    MFEWSGetFolderResponseOperation *_changeKeysResponse;	// 24 = 0x18
}

@property(readonly, nonatomic) MFEWSGetFolderResponseOperation *changeKeysResponse; // @synthesize changeKeysResponse=_changeKeysResponse;
@property(readonly, copy, nonatomic) NSString *folderName; // @synthesize folderName=_folderName;
@property(readonly, copy, nonatomic) NSString *folderIdString; // @synthesize folderIdString=_folderIdString;
- (void).cxx_destruct;	// IMP=0x000000000009d826
- (id)prepareRequest;	// IMP=0x000000000009d480
- (BOOL)isFolderRequest;	// IMP=0x000000000009d475
- (id)activityString;	// IMP=0x000000000009d408
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x000000000009d339
- (id)initWithEWSFolderIdString:(id)arg1 name:(id)arg2 gateway:(id)arg3;	// IMP=0x000000000009d01d

@end

