//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class MFEWSBodyPersistOperation, NSArray;

@protocol MFEWSBodyPersistOperationDelegate <NSObject>
- (void)bodyPersistOperation:(MFEWSBodyPersistOperation *)arg1 didPersistBodyForMessages:(NSArray *)arg2;
@end

