//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class MFEWSPersistFolderHierarchyTaskOperation, MFEWSSyncFolderHierarchyBatch;

@protocol MFEWSPersistFolderHierarchyTaskOperationDelegate <NSObject>
- (void)persistFolderHierarchyOperation:(MFEWSPersistFolderHierarchyTaskOperation *)arg1 completedBatch:(MFEWSSyncFolderHierarchyBatch *)arg2;
@end

