//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCTask.h>

@interface MFEWSTask : MCTask
{
}

- (void)operationFinished:(id)arg1;	// IMP=0x00000000000a6374
- (void)trackOperation:(id)arg1;	// IMP=0x00000000000a6278
- (id)description;	// IMP=0x00000000000a61c7

@end

