//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSRequestOperation.h>

#import <Mail/NSSecureCoding-Protocol.h>

@class NSString;

@interface MFEWSDeleteFolderRequestOperation : MFEWSRequestOperation <NSSecureCoding>
{
    NSString *_folderIdString;	// 8 = 0x8
}

+ (BOOL)supportsSecureCoding;	// IMP=0x000000000007494b
@property(readonly, copy, nonatomic) NSString *folderIdString; // @synthesize folderIdString=_folderIdString;
- (void).cxx_destruct;	// IMP=0x0000000000074c72
- (void)setupOfflineResponse;	// IMP=0x0000000000074bee
- (id)prepareRequest;	// IMP=0x0000000000074a9d
- (BOOL)isFolderRequest;	// IMP=0x0000000000074a92
- (id)activityString;	// IMP=0x0000000000074a25
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x0000000000074956
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000000000748ae
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000000074682
- (void)_ewsDeleteFolderRequestOperationCommonInitWithEWSFolderIdString:(id)arg1;	// IMP=0x000000000007464e
- (id)initWithEWSFolderIdString:(id)arg1 gateway:(id)arg2;	// IMP=0x00000000000744a4

@end

