//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSPersistenceTaskOperation.h>

@class NSArray;
@protocol MFEWSGetMessagesNeedingBodiesOperationDelegate;

@interface MFEWSGetMessagesNeedingBodiesOperation : MFEWSPersistenceTaskOperation
{
    id <MFEWSGetMessagesNeedingBodiesOperationDelegate> _delegate;	// 8 = 0x8
    NSArray *_mailboxes;	// 16 = 0x10
}

@property(readonly, copy, nonatomic) NSArray *mailboxes; // @synthesize mailboxes=_mailboxes;
@property(nonatomic) __weak id <MFEWSGetMessagesNeedingBodiesOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000000008948d
- (void)main;	// IMP=0x00000000000891b6
- (id)init;	// IMP=0x00000000000890e7
- (id)initWithMailboxes:(id)arg1;	// IMP=0x000000000008906d

@end

