//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class MFEWSPersistActionResultsOperation;

@protocol MFEWSPersistActionResultsOperationDelegate <NSObject>
- (void)persistActionResultsOperationCompleted:(MFEWSPersistActionResultsOperation *)arg1 needToReplayAction:(BOOL)arg2;
@end

