//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSRequestOperation.h>

@class MFEWSGetItemsResponseOperation;

@interface MFEWSSuppressReadReceiptsRequestOperation : MFEWSRequestOperation
{
    MFEWSGetItemsResponseOperation *_getItemsResponse;	// 8 = 0x8
}

@property(readonly, nonatomic) MFEWSGetItemsResponseOperation *getItemsResponse; // @synthesize getItemsResponse=_getItemsResponse;
- (void).cxx_destruct;	// IMP=0x00000000000a4162
- (id)prepareRequest;	// IMP=0x00000000000a3df6
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x00000000000a3d27
- (id)initWithGetItemsResponse:(id)arg1 gateway:(id)arg2;	// IMP=0x00000000000a3bc4

@end

