//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class MFEWSRetrievePersistedFolderDataOperation, NSArray, NSDictionary;

@protocol MFEWSRetrievePersistedFolderDataDelegate <NSObject>
- (void)retrievePersistedFolderDataOperation:(MFEWSRetrievePersistedFolderDataOperation *)arg1 didRetrieveFolderIDsByURL:(NSDictionary *)arg2 syncStatesByURL:(NSDictionary *)arg3 missedMailboxURLs:(NSArray *)arg4;
@end

