//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSPersistenceTaskOperation.h>

@class NSDictionary;
@protocol MFEWSBodyPersistOperationDelegate;

@interface MFEWSBodyPersistOperation : MFEWSPersistenceTaskOperation
{
    id <MFEWSBodyPersistOperationDelegate> _delegate;	// 8 = 0x8
    NSDictionary *_bodiesByMessage;	// 16 = 0x10
    NSDictionary *_calendarEventsByMessage;	// 24 = 0x18
}

@property(readonly, copy, nonatomic) NSDictionary *calendarEventsByMessage; // @synthesize calendarEventsByMessage=_calendarEventsByMessage;
@property(readonly, copy, nonatomic) NSDictionary *bodiesByMessage; // @synthesize bodiesByMessage=_bodiesByMessage;
@property(nonatomic) __weak id <MFEWSBodyPersistOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000000000691c0
- (void)main;	// IMP=0x0000000000068e0d
- (id)init;	// IMP=0x0000000000068d3e
- (id)initWithBodiesByMessage:(id)arg1 calendarEventsByMessage:(id)arg2;	// IMP=0x0000000000068c77

@end

