//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class MFEWSSyncFolderHierarchyBatch, MFEWSSyncFolderHierarchyTaskOperation;

@protocol MFEWSSyncFolderHierarchyTaskOperationDelegate <NSObject>
- (void)syncFolderHierarchyTaskOperation:(MFEWSSyncFolderHierarchyTaskOperation *)arg1 completedBatch:(MFEWSSyncFolderHierarchyBatch *)arg2;
@end

