//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSPersistenceTaskOperation.h>

@protocol MFEWSGetNewMessageActionsOperationDelegate;

@interface MFEWSGetNewMessageActionsOperation : MFEWSPersistenceTaskOperation
{
    id <MFEWSGetNewMessageActionsOperationDelegate> _delegate;	// 8 = 0x8
    long long _previousActionID;	// 16 = 0x10
}

@property(readonly, nonatomic) long long previousActionID; // @synthesize previousActionID=_previousActionID;
@property(nonatomic) __weak id <MFEWSGetNewMessageActionsOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000000089766
- (void)main;	// IMP=0x0000000000089500
- (id)initWithPreviousActionID:(long long)arg1;	// IMP=0x00000000000894bc

@end

