//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFEWSResponseOperation.h>

@class EWSGetItemResponseType, NSArray, NSMutableArray;

@interface MFEWSGetItemsResponseOperation : MFEWSResponseOperation
{
    NSMutableArray *_EWSItems;	// 8 = 0x8
    NSArray *_EWSItemIdsRequested;	// 16 = 0x10
}

@property(retain) NSArray *EWSItemIdsRequested; // @synthesize EWSItemIdsRequested=_EWSItemIdsRequested;
@property(retain) NSMutableArray *EWSItems; // @synthesize EWSItems=_EWSItems;
- (void).cxx_destruct;	// IMP=0x000000000008903c
- (void)executeOperation;	// IMP=0x0000000000088b2e
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;	// IMP=0x00000000000888d1
@property(retain) EWSGetItemResponseType *response;

@end

