//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class MFEWSMailboxItemsBatch, MFEWSMailboxReconcileTaskOperation;

@protocol MFEWSMailboxReconcileTaskOperationDelegate <NSObject>
- (void)mailboxReconcileTaskOperationFolderIsInvalid:(MFEWSMailboxReconcileTaskOperation *)arg1;
- (void)mailboxReconcileTaskOperation:(MFEWSMailboxReconcileTaskOperation *)arg1 receivedBatch:(MFEWSMailboxItemsBatch *)arg2;
@end

