//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFForeignKeyUpgradeStep : MFLibraryUpgradeStep
{
}

+ (unsigned long long)targetVersion;	// IMP=0x00000000000ad6ff
- (void)_addForeignKeysForTable:(id)arg1 createSQL:(const char *)arg2 insertSQL:(const char *)arg3;	// IMP=0x00000000000ad8c5
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x00000000000ad70a

@end

