//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Mail/MCBodyFetchContext-Protocol.h>

@class NSMutableDictionary, NSOperationQueue, NSString;

@interface MFGlobalBodyFetchContext : NSObject <MCBodyFetchContext>
{
    NSMutableDictionary *_fetchContextsByAccountIdentifier;	// 8 = 0x8
    NSOperationQueue *_workQueue;	// 16 = 0x10
}

@property(readonly, nonatomic) NSOperationQueue *workQueue; // @synthesize workQueue=_workQueue;
- (void).cxx_destruct;	// IMP=0x00000000000aeda7
- (void)cacheBodiesForMessages:(id)arg1;	// IMP=0x00000000000ae717
- (id)init;	// IMP=0x00000000000ae677

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

