//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EmailDaemon/EDGmailLabelPersistence.h>

@interface MFGmailLabelPersistence_macOS : EDGmailLabelPersistence
{
}

- (id)labelForDatabaseID:(long long)arg1;	// IMP=0x00000000000aee6a
- (id)labelURLForDatabaseID:(long long)arg1;	// IMP=0x00000000000aedcf

@end

