//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFHTMLParser : NSObject
{
}

+ (id)plainTextFromHTMLSnippet:(id)arg1;	// IMP=0x00000000000b302c
+ (id)plainTextFromHTML:(id)arg1;	// IMP=0x00000000000b3013
+ (id)plainTextFromHTML:(id)arg1 limit:(unsigned long long)arg2;	// IMP=0x00000000000b249f

@end

