//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFIMAPStoreOperation.h>

@class NSArray;

@interface MFIMAPStoreFlagsOperation : MFIMAPStoreOperation
{
}

- (id)description;	// IMP=0x00000000000d6114
@property(readonly, copy, nonatomic) NSArray *flagsToClear;
@property(readonly, copy, nonatomic) NSArray *flagsToSet;
- (unsigned char)operationType;	// IMP=0x00000000000d60e5
- (id)initWithFlagsToSet:(id)arg1 flagsToClear:(id)arg2 forUIDs:(id)arg3 inMailbox:(id)arg4;	// IMP=0x00000000000d6058

@end

