//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFIMAPCopyMessagesOperation.h>

@class NSMutableArray, NSPointerArray;

@interface MFIMAPOfflineCopyOnStupidServerOperation : MFIMAPCopyMessagesOperation
{
    NSMutableArray *_messageIds;	// 48 = 0x30
    NSPointerArray *_internalDates;	// 56 = 0x38
}

@property(retain, nonatomic) NSPointerArray *internalDates; // @synthesize internalDates=_internalDates;
@property(retain, nonatomic) NSMutableArray *messageIds; // @synthesize messageIds=_messageIds;
- (void).cxx_destruct;	// IMP=0x00000000000d7c25
- (void)_deserializeOpSpecificValuesFromData:(id)arg1 cursor:(unsigned long long *)arg2;	// IMP=0x00000000000d7b12
- (unsigned char)_magic;	// IMP=0x00000000000d7b07
- (void)serializeIntoData:(id)arg1;	// IMP=0x00000000000d7a4b

@end

