//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFIMAPOperation.h>

@class NSArray, NSIndexSet, NSPointerArray;

@interface MFIMAPStoreOperation : MFIMAPOperation
{
    NSPointerArray *_uids;	// 24 = 0x18
    NSArray *_objectsToSet;	// 32 = 0x20
    NSArray *_objectsToClear;	// 40 = 0x28
}

@property(copy, nonatomic) NSArray *objectsToClear; // @synthesize objectsToClear=_objectsToClear;
@property(copy, nonatomic) NSArray *objectsToSet; // @synthesize objectsToSet=_objectsToSet;
@property(retain, nonatomic) NSPointerArray *uids; // @synthesize uids=_uids;
- (void).cxx_destruct;	// IMP=0x00000000000d6016
- (void)serializeIntoData:(id)arg1;	// IMP=0x00000000000d5b8b
- (void)_deserializeOpSpecificValuesFromData:(id)arg1 cursor:(unsigned long long *)arg2;	// IMP=0x00000000000d5926
@property(readonly, copy, nonatomic) NSIndexSet *uidIndexSet;
- (id)_initWithObjectsToSet:(id)arg1 objectsToClear:(id)arg2 forUIDs:(id)arg3 inMailbox:(id)arg4;	// IMP=0x00000000000d556c

// Remaining properties
@property(nonatomic) BOOL usesRealUids; // @dynamic usesRealUids;

@end

