//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFIMAPStoreOperation.h>

@class NSArray;

@interface MFIMAPStoreGmailLabelsOperation : MFIMAPStoreOperation
{
}

- (id)description;	// IMP=0x00000000000d6540
@property(readonly, copy, nonatomic) NSArray *gmailLabelsToClear;
@property(readonly, copy, nonatomic) NSArray *gmailLabelsToSet;
- (unsigned char)operationType;	// IMP=0x00000000000d6511
- (id)initWithGmailLabelsToSet:(id)arg1 gmailLabelsToClear:(id)arg2 forUIDs:(id)arg3 inMailbox:(id)arg4;	// IMP=0x00000000000d6484

@end

