//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFIMAPOperation.h>

@interface MFIMAPDeleteOperation : MFIMAPOperation
{
}

- (id)description;	// IMP=0x00000000000d54bd
- (unsigned char)operationType;	// IMP=0x00000000000d54b2
- (id)initWithMailboxToDelete:(id)arg1;	// IMP=0x00000000000d54a0

@end

