//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFJunkMail : NSObject
{
}

+ (id)mapDescriptionFromMapType:(int)arg1;	// IMP=0x00000000000ccc30
+ (int)mapTypeFromMapName:(id)arg1;	// IMP=0x00000000000ccba8
+ (id)mapNameForMapType:(int)arg1;	// IMP=0x00000000000cca78

@end

