//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFMailboxDirectoryScanner : NSObject
{
}

+ (BOOL)isMailboxURL:(id)arg1;	// IMP=0x000000000016f060
+ (void)enumerateEMLXFilesInDirectory:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000000016e92b
+ (void)enumerateMailboxesAtDirectory:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000000016d5a5

@end

