//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface MFMessageSortingInformation : NSObject
{
    BOOL _skipAutomaticSecondarySort;	// 8 = 0x8
    NSDictionary *_sortValues;	// 16 = 0x10
}

@property(retain, nonatomic) NSDictionary *sortValues; // @synthesize sortValues=_sortValues;
@property(nonatomic) BOOL skipAutomaticSecondarySort; // @synthesize skipAutomaticSecondarySort=_skipAutomaticSecondarySort;
- (void)dealloc;	// IMP=0x000000000019b308

@end

