//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class MFMessageDeliverer;

@protocol MFMessageDelivererDelegate <NSObject>
- (void)messageDeliveryDidFinish:(MFMessageDeliverer *)arg1;

@optional
- (void)messageDeliveryWillBegin:(MFMessageDeliverer *)arg1;
@end

