//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class NSArray;

@protocol MFMessageConsumer <NSObject>
@property(readonly) BOOL shouldCancel;
- (void)finishedSendingMessages;
- (void)newMessagesAvailable:(NSArray *)arg1 secondaryMessages:(NSArray *)arg2 fromUpdate:(BOOL)arg3;

@optional
- (void)searchPhaseComplete;
@end

