//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFMutedMessagesHandler : NSObject
{
}

+ (BOOL)archiveOrDeleteMutedMessages;	// IMP=0x00000000001b6398
+ (void)setArchiveOrDeleteMutedMessages:(BOOL)arg1;	// IMP=0x00000000001b633e
+ (void)handleMessages:(id)arg1 changeManager:(id)arg2;	// IMP=0x00000000001b6292
+ (void)handleMessages:(id)arg1 store:(id)arg2;	// IMP=0x00000000001b61e6
+ (void)handleMutedMessages:(id)arg1 store:(id)arg2;	// IMP=0x00000000001b613a

@end

