//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Mail/EFLoggable-Protocol.h>

@class EDMessageChangeManager, MFMessageStore, NSArray, NSString;

@interface MFMutedMessageAction : NSObject <EFLoggable>
{
    NSArray *_mutedMessages;	// 8 = 0x8
    MFMessageStore *_store;	// 16 = 0x10
    EDMessageChangeManager *_changeManager;	// 24 = 0x18
}

+ (id)log;	// IMP=0x00000000001b52be
@property(readonly, nonatomic) EDMessageChangeManager *changeManager; // @synthesize changeManager=_changeManager;
@property(readonly, nonatomic) MFMessageStore *store; // @synthesize store=_store;
@property(retain, nonatomic) NSArray *mutedMessages; // @synthesize mutedMessages=_mutedMessages;
- (void).cxx_destruct;	// IMP=0x00000000001b5816
- (void)_setMutedMessagesFromMessages:(id)arg1;	// IMP=0x00000000001b5625
- (void)performActionWithChangeManager:(id)arg1;	// IMP=0x00000000001b5610
- (void)performActionWithStore:(id)arg1;	// IMP=0x00000000001b55fb
- (void)performAction;	// IMP=0x00000000001b54b9
- (id)initWithMessages:(id)arg1 changeManager:(id)arg2;	// IMP=0x00000000001b5420
- (id)initWithMessages:(id)arg1 store:(id)arg2;	// IMP=0x00000000001b5387

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

