//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMutedMessageAction.h>

@interface MFMutedMessageActionMarkAsRead : MFMutedMessageAction
{
}

- (void)performActionWithChangeManager:(id)arg1;	// IMP=0x00000000001b6090
- (void)performActionWithStore:(id)arg1;	// IMP=0x00000000001b5f77

@end

