//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EmailDaemon/EDPersistenceDatabase.h>

@interface MFPersistenceDatabase_macOS : EDPersistenceDatabase
{
    BOOL _haveSetDatabaseAttributes;	// 8 = 0x8
}

@property(nonatomic) BOOL haveSetDatabaseAttributes; // @synthesize haveSetDatabaseAttributes=_haveSetDatabaseAttributes;
- (BOOL)enforceDataProtection;	// IMP=0x00000000001c4c80
- (id)openConnectionIsWriter:(BOOL)arg1;	// IMP=0x00000000001c4bb7
- (void)_handleDatabaseException:(id)arg1;	// IMP=0x00000000001c4aa3
- (void)_setDatabaseAttributes;	// IMP=0x00000000001c4923
- (id)checkOutConnectionIsWriter:(BOOL)arg1;	// IMP=0x00000000001c489a
- (BOOL)performBlock:(CDUnknownBlockType)arg1 isWriter:(BOOL)arg2 useTransaction:(BOOL)arg3;	// IMP=0x00000000001c4309

@end

