//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EmailDaemon/EDPersistenceDatabaseSchema.h>

#import <Mail/EDPersistenceDatabaseSchemaProvider-Protocol.h>

@interface MFPersistenceDatabaseSchema_macOS : EDPersistenceDatabaseSchema <EDPersistenceDatabaseSchemaProvider>
{
}

+ (id)_macOSRecipientsTableForeignKeysToResolve:(id *)arg1 associationsToResolve:(id *)arg2;	// IMP=0x00000000001c5a18
+ (id)tablesAndForeignKeysToResolve:(id *)arg1 associationsToResolve:(id *)arg2;	// IMP=0x00000000001c591f
+ (id)additionalSchemaProviders;	// IMP=0x00000000001c58ac

@end

