//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EmailDaemon/EDProtectedDatabasePersistence.h>

@interface MFProtectedDatabasePersistence_macOS : EDProtectedDatabasePersistence
{
}

+ (id)journalDatabaseName;	// IMP=0x00000000001e4176
+ (id)protectedDatabaseName;	// IMP=0x00000000001e4162
- (BOOL)protectedDataAvailable;	// IMP=0x00000000001e4192
- (BOOL)supportsJournaling;	// IMP=0x00000000001e418a

@end

