//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@class NSArray;

@interface MFResetPartsHaveBeenCachedUpgradeStep : MFLibraryUpgradeStep
{
    NSArray *_accounts;	// 8 = 0x8
}

+ (unsigned long long)targetVersion;	// IMP=0x00000000001f8866
@property(readonly, copy, nonatomic) NSArray *accounts; // @synthesize accounts=_accounts;
- (void).cxx_destruct;	// IMP=0x00000000001f924e
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x00000000001f89de
- (id)initWithDatabaseConnection:(id)arg1;	// IMP=0x00000000001f890f
- (id)initWithDatabaseConnection:(id)arg1 accounts:(id)arg2;	// IMP=0x00000000001f8871

@end

