//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFRecalculateTotalCountsUpgradeStep : MFLibraryUpgradeStep
{
}

+ (BOOL)needToPerformFromMinorVersion:(unsigned long long)arg1 initialLastWriteMinorVersion:(unsigned long long)arg2;	// IMP=0x00000000001e5328
+ (unsigned long long)targetVersion;	// IMP=0x00000000001e5312
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x00000000001e533a
- (BOOL)shouldRecalculateMessageCounts;	// IMP=0x00000000001e531d

@end

