//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFRemoveCategoryColumnUpgradeStep : MFLibraryUpgradeStep
{
}

+ (BOOL)needToPerformFromMinorVersion:(unsigned long long)arg1 initialLastWriteMinorVersion:(unsigned long long)arg2;	// IMP=0x00000000001f4000
+ (unsigned long long)targetVersion;	// IMP=0x00000000001f3ff5
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x00000000001f4032

@end

