//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFRemoveMessagesUpgradeStep.h>

@interface MFRemoveOrphanedMailboxRowsUpgradeStep : MFRemoveMessagesUpgradeStep
{
}

+ (unsigned long long)targetVersion;	// IMP=0x00000000001f5b7d
- (id)_mailboxRowIDListWithAccountURLStrings:(id)arg1;	// IMP=0x00000000001f605e
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x00000000001f5b88

@end

