//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@class NSArray;

@interface MFReparseInvalidInReplyToHeadersUpgradeStep : MFLibraryUpgradeStep
{
    NSArray *_accounts;	// 8 = 0x8
}

+ (unsigned long long)targetVersion;	// IMP=0x00000000001f6821
@property(readonly, copy, nonatomic) NSArray *accounts; // @synthesize accounts=_accounts;
- (void).cxx_destruct;	// IMP=0x00000000001f77da
- (id)_referencesAsEncodedMessageIDStringFromMessageHeaders:(id)arg1;	// IMP=0x00000000001f7455
- (void)_reparseReferencesForRowIDsByMailboxURL:(id)arg1;	// IMP=0x00000000001f6d89
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x00000000001f6999
- (id)initWithDatabaseConnection:(id)arg1;	// IMP=0x00000000001f68ca
- (id)initWithDatabaseConnection:(id)arg1 accounts:(id)arg2;	// IMP=0x00000000001f682c

@end

