//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFReAddMessagesDeletedDateReceivedIndexUpgradeStep : MFLibraryUpgradeStep
{
}

+ (unsigned long long)targetVersion;	// IMP=0x00000000001e4e50
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x00000000001e4e5b

@end

