//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFRemoveMessagesUpgradeStep.h>

@interface MFRemoveMessagesFromGmailLabelsUpgradeStep : MFRemoveMessagesUpgradeStep
{
}

+ (unsigned long long)targetVersion;	// IMP=0x00000000001f42d4
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x00000000001f42df

@end

