//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFRulesUpgrader : NSObject
{
}

+ (id)upgradeRulesFromUbiquitousVersion3To4:(id)arg1;	// IMP=0x00000000001f9261

@end

