//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MFSearchableIndexQueryResult : NSObject
{
    NSString *_persistentID;	// 8 = 0x8
    NSString *_messageIDHeader;	// 16 = 0x10
}

@property(readonly, copy, nonatomic) NSString *messageIDHeader; // @synthesize messageIDHeader=_messageIDHeader;
@property(readonly, copy, nonatomic) NSString *persistentID; // @synthesize persistentID=_persistentID;
- (void).cxx_destruct;	// IMP=0x00000000001fe418
- (id)initWithPersistentID:(id)arg1 messageIDHeader:(id)arg2;	// IMP=0x00000000001fe33d

@end

