//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Mail/EFCancelable-Protocol.h>
#import <Mail/EFLoggable-Protocol.h>
#import <Mail/MFSearchableIndexQueryResultProvider-Protocol.h>
#import <Mail/MFSearchableIndexTopHitsResultsCollectorBuilder-Protocol.h>

@class EFFuture, EMSearchableIndexTopHitsQuery, MFMessageCriterion, NSArray, NSString;
@protocol MFMessageConsumer, MFSearchableIndexQueryResultProcessor;

@interface MFSearchableIndexTopHitsResultsCollector : NSObject <EFLoggable, MFSearchableIndexTopHitsResultsCollectorBuilder, EFCancelable, MFSearchableIndexQueryResultProvider>
{
    unsigned int _options;	// 8 = 0x8
    MFMessageCriterion *_criterion;	// 16 = 0x10
    id <MFMessageConsumer> _target;	// 24 = 0x18
    NSArray *_filterQueries;	// 32 = 0x20
    NSString *_logIdentifier;	// 40 = 0x28
    EMSearchableIndexTopHitsQuery *_topHitsQuery;	// 48 = 0x30
    id <MFSearchableIndexQueryResultProcessor> _processor;	// 56 = 0x38
}

+ (void)setMostRecentTopHitsQueryResult:(id)arg1;	// IMP=0x00000000002016e0
+ (id)mostRecentTopHitsQueryResult;	// IMP=0x00000000002016cf
+ (id)log;	// IMP=0x0000000000201606
@property(retain, nonatomic) id <MFSearchableIndexQueryResultProcessor> processor; // @synthesize processor=_processor;
@property(retain, nonatomic) EMSearchableIndexTopHitsQuery *topHitsQuery; // @synthesize topHitsQuery=_topHitsQuery;
@property(copy, nonatomic) NSString *logIdentifier; // @synthesize logIdentifier=_logIdentifier;
@property(copy, nonatomic) NSArray *filterQueries; // @synthesize filterQueries=_filterQueries;
@property(retain, nonatomic) id <MFMessageConsumer> target; // @synthesize target=_target;
@property(nonatomic) unsigned int options; // @synthesize options=_options;
@property(retain, nonatomic) MFMessageCriterion *criterion; // @synthesize criterion=_criterion;
- (void).cxx_destruct;	// IMP=0x0000000000201f28
- (BOOL)isCancelled;	// IMP=0x0000000000201dfb
- (void)cancel;	// IMP=0x0000000000201d7a
@property(readonly, nonatomic) EFFuture *gatheredFuture;
- (void)_processTopHitsQueryResult:(id)arg1;	// IMP=0x0000000000201af4
- (void)start;	// IMP=0x0000000000201ab7
- (id)initWithSearchPhrase:(id)arg1 processor:(id)arg2 builder:(CDUnknownBlockType)arg3;	// IMP=0x00000000002016f4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

