//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class EFFuture, MFMessageCriterion;
@protocol MFMessageConsumer;

@protocol MFSearchableIndexQueryResultProvider <NSObject>
@property(readonly, nonatomic) EFFuture *gatheredFuture;
@property(readonly, nonatomic) id <MFMessageConsumer> target;
@property(readonly, nonatomic) unsigned int options;
@property(readonly, nonatomic) MFMessageCriterion *criterion;
- (void)start;
@end

