//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFSearchableIndexQueryResultProviderBuilder-Protocol.h>

@class EMSearchableIndexQueryExpression;

@protocol MFSearchableIndexQueryResultCollectorBuilder <MFSearchableIndexQueryResultProviderBuilder>
@property(copy, nonatomic) CDUnknownBlockType recoveryBlock;
@property(nonatomic) BOOL live;
@property(retain, nonatomic) EMSearchableIndexQueryExpression *originalExpression;
@end

