//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFSearchableIndexQueryResultProviderBuilder-Protocol.h>

@class NSArray;

@protocol MFSearchableIndexTopHitsResultsCollectorBuilder <MFSearchableIndexQueryResultProviderBuilder>
@property(copy, nonatomic) NSArray *filterQueries;
@end

