//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class MFMessageCriterion, NSString;
@protocol MFMessageConsumer;

@protocol MFSearchableIndexQueryResultProviderBuilder <NSObject>
@property(copy, nonatomic) NSString *logIdentifier;
@property(nonatomic) unsigned int options;
@property(retain, nonatomic) MFMessageCriterion *criterion;
@property(retain, nonatomic) id <MFMessageConsumer> target;
@end

