//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFSmartMailboxesUpgrader : NSObject
{
}

+ (id)_upgradeSmartMailboxFromUbiquitousVersion3To4:(id)arg1;	// IMP=0x000000000020bb0d
+ (id)upgradeSmartMailboxesFromUbiquitousVersion3To4:(id)arg1;	// IMP=0x000000000020b92b

@end

