//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFMessageDeliverer.h>

@class MFSMTPAccount;

@interface MFSMTPDeliverer : MFMessageDeliverer
{
}

- (long long)deliverMessageHeaderData:(id)arg1 bodyData:(id)arg2 toRecipients:(id)arg3;	// IMP=0x000000000021ea89
@property(retain, nonatomic) MFSMTPAccount *account;

@end

