//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/NSObject-Protocol.h>

@class MCMessage, MFSnippetCalculator, NSArray, NSString;

@protocol MFSnippetCalculatorDelegate <NSObject>
- (void)snippetCalculator:(MFSnippetCalculator *)arg1 didSkipMessages:(NSArray *)arg2;
- (void)snippetCalculator:(MFSnippetCalculator *)arg1 didCalculateSnippet:(NSString *)arg2 forMessage:(MCMessage *)arg3;
@end

