//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFRemoveMessagesUpgradeStep.h>

@interface MFTemporaryUIDsCleanupUpgradeStep : MFRemoveMessagesUpgradeStep
{
}

+ (unsigned long long)targetVersion;	// IMP=0x000000000023273c
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x0000000000232747

@end

