//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@interface MFUpdateMuteThreadConversationFlagUpgradeStep : MFLibraryUpgradeStep
{
}

+ (BOOL)needToPerformFromMinorVersion:(unsigned long long)arg1 initialLastWriteMinorVersion:(unsigned long long)arg2;	// IMP=0x0000000000236e77
+ (unsigned long long)targetVersion;	// IMP=0x0000000000236e6c
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x0000000000236ebc

@end

