//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

#import <Mail/EFLoggable-Protocol.h>
#import <Mail/MFUpdateAttachmentsWithAttachmentIDUpgradeStepDataSource-Protocol.h>

@class NSDirectoryEnumerator, NSRegularExpression, NSString;
@protocol MFUpdateAttachmentsWithAttachmentIDUpgradeStepDataSource;

@interface MFUpdateAttachmentsWithAttachmentIDUpgradeStep : MFLibraryUpgradeStep <MFUpdateAttachmentsWithAttachmentIDUpgradeStepDataSource, EFLoggable>
{
    NSDirectoryEnumerator *_directoryEnumerator;	// 8 = 0x8
    NSRegularExpression *_attachmentFileRegularExpression;	// 16 = 0x10
    id <MFUpdateAttachmentsWithAttachmentIDUpgradeStepDataSource> _dataSource;	// 24 = 0x18
}

+ (unsigned long long)targetVersion;	// IMP=0x0000000000235c4b
+ (id)log;	// IMP=0x0000000000235b82
@property(nonatomic) __weak id <MFUpdateAttachmentsWithAttachmentIDUpgradeStepDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) NSRegularExpression *attachmentFileRegularExpression; // @synthesize attachmentFileRegularExpression=_attachmentFileRegularExpression;
@property(retain, nonatomic) NSDirectoryEnumerator *directoryEnumerator; // @synthesize directoryEnumerator=_directoryEnumerator;
- (void).cxx_destruct;	// IMP=0x0000000000236936
- (BOOL)updateAttachmentsWithAttachmentIDUpgradeStep:(id)arg1 isDirectoryForFileURL:(id)arg2;	// IMP=0x000000000023688b
- (CDUnknownBlockType)skipDescendantsBlockForUpdateAttachmentsWithAttachmentIDUpgradeStep:(id)arg1;	// IMP=0x0000000000236782
- (id)fileURLEnumeratorForUpdateAttachmentsWithAttachmentIDUpgradeStep:(id)arg1;	// IMP=0x0000000000236770
- (void)processAttachmentsIfNecessaryAtFileURL:(id)arg1 isDirectory:(BOOL)arg2 skipDescendantsBlock:(CDUnknownBlockType)arg3 resultsBlock:(CDUnknownBlockType)arg4;	// IMP=0x00000000002362f5
- (void)_insertAttachmentEntryWithConnection:(id)arg1 messageIdentifier:(id)arg2 attachmentID:(id)arg3 name:(id)arg4;	// IMP=0x000000000023605c
- (void)_migrateDataFromOldAttachmentsTableUsingConnection:(id)arg1 dataSource:(id)arg2;	// IMP=0x0000000000235d41
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x0000000000235c56

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

