//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Email/EMUserProfileProvider.h>

#import <Mail/EMUserProfileProviderSubclassMethods-Protocol.h>

@class NSString;

@interface MFUserProfileProvider_macOS : EMUserProfileProvider <EMUserProfileProviderSubclassMethods>
{
}

+ (id)defaultProvider;	// IMP=0x0000000000238413
- (id)_accountsEmailAddresses;	// IMP=0x0000000000238478

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

