//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSAppleScript.h>

@interface NSAppleScript (MessageRuleAdditions)
+ (id)appleEventDescriptionWithEventClass:(unsigned int)arg1 eventID:(unsigned int)arg2 andArguments:(id)arg3;	// IMP=0x00000000001b8686
+ (id)appleEventDescriptionWithName:(id)arg1 andArguments:(id)arg2;	// IMP=0x00000000001b84fe
+ (id)_newScriptAtPath:(id)arg1 errorInfo:(id *)arg2;	// IMP=0x00000000001b83c2
@end

