//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (MailFoundationAdditions)
- (id)objectForIntegerKey:(long long)arg1;	// IMP=0x00000000000addb7
- (struct CGSize)sizeForKey:(id)arg1;	// IMP=0x00000000000adca2
- (double)cgfloatForKey:(id)arg1;	// IMP=0x00000000000adc32
- (float)floatForKey:(id)arg1;	// IMP=0x00000000000adbc2
- (long long)integerForKey:(id)arg1;	// IMP=0x00000000000adb56
- (BOOL)boolForKey:(id)arg1;	// IMP=0x00000000000adae9
- (id)mutableSomewhatDeepCopy;	// IMP=0x00000000001b8b22
@end

