//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSMutableDictionary (MailFoundationAdditions)
- (void)setObject:(id)arg1 forIntegerKey:(long long)arg2;	// IMP=0x00000000000ae139
- (void)setSize:(struct CGSize)arg1 forKey:(id)arg2;	// IMP=0x00000000000ae02b
- (void)setCGFloat:(double)arg1 forKey:(id)arg2;	// IMP=0x00000000000adfa5
- (void)setFloat:(float)arg1 forKey:(id)arg2;	// IMP=0x00000000000adf1f
- (void)setInteger:(long long)arg1 forKey:(id)arg2;	// IMP=0x00000000000ade9e
- (void)setBool:(BOOL)arg1 forKey:(id)arg2;	// IMP=0x00000000000ade1d
@end

