//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreData/NSPersistentStoreCoordinator.h>

@interface NSPersistentStoreCoordinator (MailAdditions)
- (id)_addSQLPersistentStoreFromPath:(id)arg1 URL:(id)arg2 type:(long long)arg3 recoveringFromError:(id)arg4;	// IMP=0x000000000003cfe0
- (id)addSQLPersistentStoreFromPath:(id)arg1 type:(long long)arg2 error:(id *)arg3;	// IMP=0x000000000003ce2f
@end

