//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSUserDefaults.h>

@class NSURL;

@interface NSUserDefaults (MailAdditions)
- (id)_mf_objectForKey:(id)arg1 version:(unsigned long long)arg2;	// IMP=0x000000000005262b
- (void)setDisplayName:(id)arg1 forFlagColor:(BOOL)arg2;	// IMP=0x000000000005241e
- (id)displayNameForFlagColor:(BOOL)arg1;	// IMP=0x0000000000052265
@property(nonatomic) BOOL autosaveWindows;
@property(readonly, nonatomic) double autoSaveStoreDelay;
@property(readonly, nonatomic) double autoSaveDelay;
@property(retain, nonatomic) NSURL *downloadDirectoryURL;
@end

